// VAULT REWARDS DATA - VERBATIM FROM SPECIFICATION
// DO NOT EDIT ANY TEXT, LINKS, OR TIMING

export interface VaultReward {
  id: number;
  title: string;
  unlockRule: string;
  when?: string;
  rewardTitle: string;
  rewardLink?: string;
  rewardText?: string;
  enjoymentTime: string;
  phase: 'ignition' | 'pressure-signal' | 'proof-escalation' | 'consolidation-signal' | 'leverage-selection' | 'irreversible-tier' | 'elite-tier' | 'end-of-year-legacy' | 'mythic-high-leverage' | 'sovereign-tier' | 'final-month';
}

export const PHASE_LABELS = {
  'ignition': 'Ignition',
  'pressure-signal': 'Pressure & Signal',
  'proof-escalation': 'Proof & Escalation',
  'consolidation-signal': 'Consolidation & Signal',
  'leverage-selection': 'Leverage & Selection',
  'irreversible-tier': 'Irreversible Tier',
  'elite-tier': 'Elite Tier',
  'end-of-year-legacy': 'End-of-Year / Legacy Tier',
  'mythic-high-leverage': 'Mythic / High-Leverage Tier',
  'sovereign-tier': 'Sovereign / High-Status Operator Tier',
  'final-month': 'The Final Month',
} as const;

export const PHASE_RANGES = {
  'ignition': '1–10',
  'pressure-signal': '11–25',
  'proof-escalation': '26–45',
  'consolidation-signal': '46–60',
  'leverage-selection': '61–75',
  'irreversible-tier': '76–99',
  'elite-tier': '100–151',
  'end-of-year-legacy': '152–200',
  'mythic-high-leverage': '201–250',
  'sovereign-tier': '251–300',
  'final-month': '301–360',
} as const;

export const VAULT_REWARDS: VaultReward[] = [
  // ========== IGNITION (Weeks 1–2) - Rewards 1-10 ==========
  {
    id: 1,
    title: 'BUILD BEGINS',
    unlockRule: 'Yesterday was GREEN (all planned tasks executed)',
    when: 'Any day in Week 1',
    rewardTitle: 'Paul Graham — Maker\'s Schedule',
    rewardLink: 'https://paulgraham.com/makersschedule.html',
    enjoymentTime: '20 minutes',
    phase: 'ignition',
  },
  {
    id: 2,
    title: 'FIRST NO DOES NOT KILL YOU',
    unlockRule: 'Sent 5 cold messages to local businesses',
    when: 'Week 1',
    rewardTitle: 'Naval Ravikant — How to Get Rich (thread)',
    rewardLink: 'https://nav.al/rich',
    enjoymentTime: '25 minutes',
    phase: 'ignition',
  },
  {
    id: 3,
    title: 'SILENCE IS NORMAL',
    unlockRule: '24 hours passed with no replies, and you still executed next task',
    when: 'Week 1',
    rewardTitle: 'Cal Newport — Deep Work Summary',
    rewardLink: 'https://calnewport.com/deep-work-rules-for-focused-success-in-a-distracted-world/',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 4,
    title: 'UGLY BUT REAL',
    unlockRule: 'Shipped any live page (even ugly)',
    when: 'Week 1–2',
    rewardTitle: 'First SpaceX Falcon 1 failure story',
    rewardLink: 'https://en.wikipedia.org/wiki/Falcon_1',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 5,
    title: 'DISCIPLINE IS BINARY',
    unlockRule: '3 consecutive days, discipline score = 100',
    when: 'Week 1–2',
    rewardTitle: 'James Clear — Discipline Article',
    rewardLink: 'https://jamesclear.com/discipline',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 6,
    title: 'FIRST REAL PITCH',
    unlockRule: 'Delivered 1 pitch (DM, call, or walk-in)',
    when: 'Week 1–2',
    rewardTitle: 'Watch one MrBeast video of your choice',
    rewardLink: 'https://www.youtube.com/@MrBeast',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 7,
    title: 'CONSISTENCY > TALENT',
    unlockRule: 'Executed the same task 3 days in a row',
    when: 'Week 2',
    rewardTitle: 'Wikipedia — Compound Effect',
    rewardLink: 'https://en.wikipedia.org/wiki/Compound_interest',
    enjoymentTime: '25 minutes',
    phase: 'ignition',
  },
  {
    id: 8,
    title: 'FIRST FOLLOW-UP',
    unlockRule: 'Followed up with 3 businesses',
    when: 'Week 2',
    rewardTitle: 'Watch one YouTube interview (founder of your choice)',
    rewardLink: 'https://www.youtube.com/watch?v=G5e5dXfR9Yk',
    enjoymentTime: '35 minutes',
    phase: 'ignition',
  },
  {
    id: 9,
    title: 'NO HIDING',
    unlockRule: 'Publicly expose your service (post, bio, or message)',
    when: 'Week 2',
    rewardTitle: 'Airbnb origin story',
    rewardLink: 'https://en.wikipedia.org/wiki/Airbnb#History',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 10,
    title: 'WEEK ONE SURVIVED',
    unlockRule: 'Week ended GREEN',
    when: 'End of Week 1',
    rewardTitle: 'Watch any Formula 1 race highlights',
    rewardLink: 'https://www.youtube.com/@Formula1',
    enjoymentTime: '45 minutes',
    phase: 'ignition',
  },

  // ========== PRESSURE & SIGNAL (Weeks 3–6) - Rewards 11-25 ==========
  {
    id: 11,
    title: 'TEN PITCHES DEEP',
    unlockRule: '10 pitches total sent',
    when: 'End of Week 1 (first full execution week completed)',
    rewardTitle: 'Hans Zimmer — Time',
    rewardLink: 'https://www.youtube.com/watch?v=RxabLA7UQ9k',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 12,
    title: 'FIRST STRONG REJECTION',
    unlockRule: 'Received a clear "no"',
    when: 'Day 10 (no skipped days in a row)',
    rewardTitle: 'Stripe origin story',
    rewardLink: 'https://en.wikipedia.org/wiki/Stripe,_Inc',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 13,
    title: 'MOMENTUM EXISTS',
    unlockRule: '2 GREEN days back-to-back',
    when: 'After first measurable output shipped',
    rewardTitle: 'Dark ambient focus mix',
    rewardLink: 'https://www.youtube.com/watch?v=QnAqgM6Z7rc',
    enjoymentTime: '40 min',
    phase: 'pressure-signal',
  },
  {
    id: 14,
    title: 'FIRST YES (INTEREST)',
    unlockRule: 'Someone asks a follow-up question',
    when: 'End of Week 2',
    rewardTitle: 'Watch one long podcast clip (Lex / Naval / YC)',
    rewardLink: 'https://www.youtube.com/@lexfridman',
    enjoymentTime: '45 min',
    phase: 'pressure-signal',
  },
  {
    id: 15,
    title: 'SYSTEM THINKER',
    unlockRule: 'Document your weekly flow clearly',
    when: 'First Sunday night review completed honestly',
    rewardTitle: 'Systems Thinking',
    rewardLink: 'https://en.wikipedia.org/wiki/Systems_thinking',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 16,
    title: 'WEEK TWO CLEAN',
    unlockRule: 'Week 2 GREEN',
    when: 'Day 14, zero-rule violations',
    rewardTitle: 'Go sit anywhere comfortable outside home, no phone',
    enjoymentTime: '1 hour',
    phase: 'pressure-signal',
  },
  {
    id: 17,
    title: 'FIRST CUSTOMER CONTACT',
    unlockRule: 'Real conversation with a potential buyer',
    when: 'After first public-facing action',
    rewardTitle: 'WhatsApp history',
    rewardLink: 'https://en.wikipedia.org/wiki/WhatsApp',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 18,
    title: '20 PITCHES MARK',
    unlockRule: '20 total pitches sent',
    when: 'End of Week 3',
    rewardTitle: 'Watch any documentary segment you choose',
    enjoymentTime: '1 hour',
    phase: 'pressure-signal',
  },
  {
    id: 19,
    title: 'PROOF OF LIFE',
    unlockRule: 'Startup landing page live',
    when: 'First discomfort task completed',
    rewardTitle: 'OpenAI founding',
    rewardLink: 'https://en.wikipedia.org/wiki/OpenAI',
    enjoymentTime: '35 min',
    phase: 'pressure-signal',
  },
  {
    id: 20,
    title: 'FIRST MONEY (ANY AMOUNT)',
    unlockRule: 'Receive any payment',
    when: 'Day 21 (habit lock-in threshold)',
    rewardTitle: 'Go eat anything you genuinely enjoy',
    enjoymentTime: '1.5 hours',
    phase: 'pressure-signal',
  },
  {
    id: 21,
    title: 'NO ESCAPE WEEK',
    unlockRule: 'No skipped days for 7 days',
    when: 'Start of Week 4',
    rewardTitle: 'Watch any full movie you choose',
    enjoymentTime: '2 hours',
    phase: 'pressure-signal',
  },
  {
    id: 22,
    title: 'REPEATABLE ACTION',
    unlockRule: 'Same outreach process repeated twice',
    when: 'After first rejection or failure logged',
    rewardTitle: 'Leverage concept',
    rewardLink: 'https://nav.al/leverage',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 23,
    title: 'WEEK THREE GREEN',
    unlockRule: 'Week 3 GREEN',
    when: 'Mid–Week 4',
    rewardTitle: 'Formula 1 full race replay',
    enjoymentTime: '2 hours',
    phase: 'pressure-signal',
  },
  {
    id: 24,
    title: 'FIRST CLIENT DELIVERABLE',
    unlockRule: 'Deliver anything to a client',
    when: 'First month planning doc finalized',
    rewardTitle: 'Silence (intentional)',
    rewardLink: 'https://www.youtube.com/watch?v=JTEFKFiXSx4',
    enjoymentTime: '20 min',
    phase: 'pressure-signal',
  },
  {
    id: 25,
    title: 'YOU ARE IN THE GAME',
    unlockRule: 'Cash + startup both active',
    when: 'End of Week 4',
    rewardTitle: 'Do anything relaxing, no guilt',
    enjoymentTime: '2 hours',
    phase: 'pressure-signal',
  },

  // ========== PROOF & ESCALATION (Weeks 4–6) - Rewards 26-45 ==========
  {
    id: 26,
    title: 'PASSPORT MOVE',
    unlockRule: 'Applied for passport',
    when: 'First 30-day streak attempt completed',
    rewardTitle: 'International travel documentary',
    enjoymentTime: '1 hour',
    phase: 'proof-escalation',
  },
  {
    id: 27,
    title: 'FIRST CLIENT RETENTION',
    unlockRule: 'Client responds positively after delivery',
    when: 'After first self-imposed punishment survived',
    rewardTitle: 'Watch any YouTube content freely',
    enjoymentTime: '1 hour',
    phase: 'proof-escalation',
  },
  {
    id: 28,
    title: 'WEEK FOUR CLEAN',
    unlockRule: 'Week 4 GREEN',
    when: 'Start of Week 5',
    rewardTitle: 'Leave home alone, reflect',
    enjoymentTime: '2 hours',
    phase: 'proof-escalation',
  },
  {
    id: 29,
    title: 'SYSTEM > MOOD',
    unlockRule: 'Execute despite low motivation',
    when: 'First small win documented',
    rewardTitle: 'Stoicism overview',
    rewardLink: 'https://en.wikipedia.org/wiki/Stoicism',
    enjoymentTime: '30 min',
    phase: 'proof-escalation',
  },
  {
    id: 30,
    title: 'FIRST REFERRAL ATTEMPT',
    unlockRule: 'Ask for referral once',
    when: 'Day 35 (momentum checkpoint)',
    rewardTitle: 'Watch one elite founder talk',
    enjoymentTime: '45 min',
    phase: 'proof-escalation',
  },
  {
    id: 31,
    title: '40 PITCHES TOTAL',
    unlockRule: '40 pitches sent',
    when: 'End of Week 5',
    rewardTitle: 'Full Formula 1 race',
    enjoymentTime: '2.5 hours',
    phase: 'proof-escalation',
  },
  {
    id: 32,
    title: 'WEEK FIVE SURVIVED',
    unlockRule: 'Week 5 GREEN',
    when: 'First process/system written down',
    rewardTitle: 'Free roam evening',
    enjoymentTime: '2 hours',
    phase: 'proof-escalation',
  },
  {
    id: 33,
    title: 'REAL USER FEEDBACK',
    unlockRule: 'User gives feedback',
    when: 'After removing one distraction permanently',
    rewardTitle: 'Product-market fit reading',
    rewardLink: 'https://en.wikipedia.org/wiki/Product-market_fit',
    enjoymentTime: '30 min',
    phase: 'proof-escalation',
  },
  {
    id: 34,
    title: 'CONSISTENCY IDENTITY',
    unlockRule: '21 days discipline intact',
    when: 'Mid–Week 6',
    rewardTitle: 'Watch anything you want',
    enjoymentTime: '3 hours',
    phase: 'proof-escalation',
  },
  {
    id: 35,
    title: 'FIRST MONTH COMPLETE',
    unlockRule: 'Month ends GREEN',
    when: 'End of Week 6',
    rewardTitle: 'Full rest evening',
    enjoymentTime: '3 hours',
    phase: 'proof-escalation',
  },
  {
    id: 36,
    title: 'STILL STANDING',
    unlockRule: 'Execute tasks on a day you explicitly wanted to quit',
    when: 'First measurable improvement vs baseline',
    rewardTitle: 'Marcus Aurelius — Meditations (selected)',
    rewardLink: 'https://en.wikipedia.org/wiki/Meditations',
    enjoymentTime: '30 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 37,
    title: 'CLIENT TWO HUNT',
    unlockRule: 'Actively pitch for a second client (minimum 5 pitches in one day)',
    when: 'Start of Week 7',
    rewardTitle: 'Watch one long-form business breakdown',
    rewardLink: 'https://www.youtube.com/@HowMoneyWorks',
    enjoymentTime: '45 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 38,
    title: 'NO PERFECTION WEEK',
    unlockRule: 'Ship something imperfect every day for 5 days',
    when: 'First "worked when tired" day',
    rewardTitle: 'Reid Hoffman — Blitzscaling concept',
    rewardLink: 'https://en.wikipedia.org/wiki/Blitzscaling',
    enjoymentTime: '30 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 39,
    title: 'SYSTEM DOCUMENTED',
    unlockRule: 'Write your exact outreach system step-by-step',
    when: 'End of Week 7',
    rewardTitle: 'Watch one full documentary episode',
    enjoymentTime: '1.5 hours',
    phase: 'proof-escalation',
  },
  {
    id: 40,
    title: 'FIRST REPEAT PAYMENT',
    unlockRule: 'Same client pays again OR confirms continuation',
    when: 'Day 50 (discipline stress test)',
    rewardTitle: 'Go eat outside alone, intentionally',
    enjoymentTime: '1.5 hours',
    phase: 'proof-escalation',
  },
  {
    id: 41,
    title: 'PUBLIC COMMITMENT',
    unlockRule: 'Publicly state a goal with a deadline (online or to real people)',
    when: 'Start of Week 8',
    rewardTitle: 'Accountability & commitment',
    rewardLink: 'https://en.wikipedia.org/wiki/Commitment_device',
    enjoymentTime: '30 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 42,
    title: '60 PITCHES TOTAL',
    unlockRule: 'Reach 60 total pitches',
    when: 'After first external validation',
    rewardTitle: 'Formula 1 race replay of your choice',
    enjoymentTime: '2.5 hours',
    phase: 'proof-escalation',
  },
  {
    id: 43,
    title: 'STARTUP EXISTS PUBLICLY',
    unlockRule: 'Someone outside you can see and describe your startup',
    when: 'Mid–Week 8',
    rewardTitle: 'Y Combinator — How to Measure Startup Progress',
    rewardLink: 'https://www.ycombinator.com/library/5z-how-to-measure-startup-progress',
    enjoymentTime: '35 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 44,
    title: 'WEEK SIX GREEN',
    unlockRule: 'Entire Week 6 GREEN',
    when: 'First boring week fully completed',
    rewardTitle: 'Full free evening, no work',
    enjoymentTime: '3 hours',
    phase: 'proof-escalation',
  },
  {
    id: 45,
    title: 'SEASON 1 SURVIVED',
    unlockRule: 'Complete Weeks 1–6 without abandoning either engine',
    when: 'End of Week 8',
    rewardTitle: 'Watch any full movie you choose',
    enjoymentTime: '3 hours',
    phase: 'proof-escalation',
  },

  // ========== CONSOLIDATION & SIGNAL (Season 2) - Rewards 46-60 ==========
  {
    id: 46,
    title: 'TWO CLIENTS ACTIVE',
    unlockRule: 'Two paying or committed clients simultaneously',
    when: 'After fixing a mistake instead of quitting',
    rewardTitle: 'Network effects',
    rewardLink: 'https://en.wikipedia.org/wiki/Network_effect',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 47,
    title: 'CASH ENGINE STABLE WEEK',
    unlockRule: 'Cash engine executed daily for 7 days',
    when: 'Start of Week 9',
    rewardTitle: 'Watch any YouTube content freely',
    enjoymentTime: '1.5 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 48,
    title: 'FIRST REFERRAL ASK',
    unlockRule: 'Ask a client for a referral',
    when: 'First long execution session (3–4h)',
    rewardTitle: 'Word-of-mouth marketing',
    rewardLink: 'https://en.wikipedia.org/wiki/Word-of-mouth_marketing',
    enjoymentTime: '25 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 49,
    title: 'STARTUP USER #5',
    unlockRule: '5 real users interact with startup',
    when: 'End of Week 9',
    rewardTitle: 'Product traction',
    rewardLink: 'https://en.wikipedia.org/wiki/Traction_(business)',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 50,
    title: 'NO-ESCAPE FORTNIGHT',
    unlockRule: '14 days, no RED days',
    when: 'Day 63 (two months consistency)',
    rewardTitle: 'Watch two Formula 1 races (highlights or full)',
    enjoymentTime: '3 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 51,
    title: 'SYSTEM IMPROVER',
    unlockRule: 'Improve one process based on rejection data',
    when: 'Start of Week 10',
    rewardTitle: 'Feedback loops',
    rewardLink: 'https://en.wikipedia.org/wiki/Feedback',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 52,
    title: 'FIRST MONTHLY TARGET HIT',
    unlockRule: 'Hit your self-set monthly cash target',
    when: 'After saying "no" to a distraction',
    rewardTitle: 'Eat anywhere you choose, no rush',
    enjoymentTime: '2 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 53,
    title: 'STARTUP SURVIVAL DECISION',
    unlockRule: 'Explicitly decide "continue" or "kill" with reasons',
    when: 'Mid–Week 10',
    rewardTitle: 'Sunk cost fallacy',
    rewardLink: 'https://en.wikipedia.org/wiki/Sunk_cost',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 54,
    title: '100 PITCHES TOTAL',
    unlockRule: '100 total outreach attempts',
    when: 'First silent grind week (no sharing)',
    rewardTitle: 'Any long-form interview or documentary',
    enjoymentTime: '2 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 55,
    title: 'WEEK TEN GREEN',
    unlockRule: 'Week 10 GREEN',
    when: 'End of Week 10',
    rewardTitle: 'Evening out, intentional reflection',
    enjoymentTime: '2 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 56,
    title: 'CASH WITHOUT THINKING',
    unlockRule: 'Client arrives via system, not effort spike',
    when: 'First time executing without motivation',
    rewardTitle: 'Automation',
    rewardLink: 'https://en.wikipedia.org/wiki/Automation',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 57,
    title: 'STARTUP SIGNAL WEEK',
    unlockRule: 'Users return without reminder',
    when: 'Start of Week 11',
    rewardTitle: 'Retention',
    rewardLink: 'https://en.wikipedia.org/wiki/Customer_retention',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 58,
    title: 'DISCIPLINE IDENTITY LOCKED',
    unlockRule: '45 days zero violations',
    when: 'First visible compounding result',
    rewardTitle: 'Watch anything you want',
    enjoymentTime: '3 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 59,
    title: 'SYSTEM OWNER',
    unlockRule: 'You can skip a day and system still runs',
    when: 'End of Week 11',
    rewardTitle: 'Leverage (Naval)',
    rewardLink: 'https://nav.al/leverage',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 60,
    title: 'SEASON 2 MIDPOINT',
    unlockRule: 'Reach Week 14 with both engines alive',
    when: 'Day 77 (identity shift phase)',
    rewardTitle: 'Full half-day off',
    enjoymentTime: '4 hours',
    phase: 'consolidation-signal',
  },

  // ========== LEVERAGE & SELECTION - Rewards 61-75 ==========
  {
    id: 61,
    title: 'HARD NO ACCEPTED',
    unlockRule: 'Kill a feature or idea publicly',
    when: 'Start of Week 12',
    rewardTitle: 'Opportunity cost',
    rewardLink: 'https://en.wikipedia.org/wiki/Opportunity_cost',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 62,
    title: 'CASH ENGINE SOP',
    unlockRule: 'Create step-by-step SOP for cash engine',
    when: 'After fixing something broken for weeks',
    rewardTitle: 'Systems over goals',
    rewardLink: 'https://jamesclear.com/goals-systems',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 63,
    title: '$X WEEK REPEAT',
    unlockRule: 'Same revenue two weeks in a row',
    when: 'Mid–Week 12',
    rewardTitle: 'Any documentary of choice',
    enjoymentTime: '2 hours',
    phase: 'leverage-selection',
  },
  {
    id: 64,
    title: 'STARTUP CLEAR WINNER',
    unlockRule: 'One metric clearly dominates',
    when: 'First uncomfortable outreach/action',
    rewardTitle: 'Focus',
    rewardLink: 'https://en.wikipedia.org/wiki/Attention',
    enjoymentTime: '25 min',
    phase: 'leverage-selection',
  },
  {
    id: 65,
    title: 'FIRST DELEGATION',
    unlockRule: 'Delegate or automate one task',
    when: 'End of Week 12',
    rewardTitle: 'Watch any content freely',
    enjoymentTime: '1.5 hours',
    phase: 'leverage-selection',
  },
  {
    id: 66,
    title: 'NOISE ELIMINATED',
    unlockRule: 'Remove one distraction permanently',
    when: 'First real confidence spike',
    rewardTitle: 'Minimalism',
    rewardLink: 'https://en.wikipedia.org/wiki/Minimalism',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 67,
    title: 'WEEKLY SCOREBOARD STREAK',
    unlockRule: '4 consecutive GREEN weeks',
    when: 'Start of Week 13',
    rewardTitle: 'Formula 1 full race',
    enjoymentTime: '2.5 hours',
    phase: 'leverage-selection',
  },
  {
    id: 68,
    title: 'REAL COMPETITION AWARENESS',
    unlockRule: 'Analyze 3 competitors properly',
    when: 'After choosing long-term over short-term',
    rewardTitle: 'Competitive advantage',
    rewardLink: 'https://en.wikipedia.org/wiki/Competitive_advantage',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 69,
    title: 'CLIENT DEPENDENCE BROKEN',
    unlockRule: 'No single client >50% income',
    when: 'End of Week 13',
    rewardTitle: 'Evening out',
    enjoymentTime: '2 hours',
    phase: 'leverage-selection',
  },
  {
    id: 70,
    title: 'SYSTEM RESILIENCE',
    unlockRule: 'One failure handled without panic',
    when: 'Day 90 (quarter milestone)',
    rewardTitle: 'Antifragility',
    rewardLink: 'https://en.wikipedia.org/wiki/Antifragility',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 71,
    title: 'LEVERAGE & SELECTION 71',
    unlockRule: 'Reward 71 unlock rule',
    when: 'Start of Week 14',
    rewardTitle: 'Reward 71',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 72,
    title: 'LEVERAGE & SELECTION 72',
    unlockRule: 'Reward 72 unlock rule',
    when: 'First week without internal resistance',
    rewardTitle: 'Reward 72',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 73,
    title: 'LEVERAGE & SELECTION 73',
    unlockRule: 'Reward 73 unlock rule',
    when: 'Mid–Week 14',
    rewardTitle: 'Reward 73',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 74,
    title: 'LEVERAGE & SELECTION 74',
    unlockRule: 'Reward 74 unlock rule',
    when: 'After delivering something publicly',
    rewardTitle: 'Reward 74',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 75,
    title: 'LEVERAGE & SELECTION 75',
    unlockRule: 'Reward 75 unlock rule',
    when: 'End of Week 14',
    rewardTitle: 'Reward 75',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },

  // ========== IRREVERSIBLE TIER - Rewards 76-99 ==========
  {
    id: 76,
    title: 'FIRST INTERNATIONAL CLIENT',
    unlockRule: 'Receive payment or signed agreement from a client outside Ethiopia',
    when: 'First "this is who I am now" moment',
    rewardTitle: 'Watch any full international business documentary',
    rewardLink: 'https://www.youtube.com/watch?v=R8m3W9y0P5Y',
    enjoymentTime: '2.5 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 77,
    title: 'MONTHLY INCOME FLOOR SET',
    unlockRule: 'Earn the same minimum income for 2 consecutive months',
    when: 'Start of Week 15',
    rewardTitle: 'Read + explore: Financial Independence',
    rewardLink: 'https://en.wikipedia.org/wiki/Financial_independence',
    enjoymentTime: '40 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 78,
    title: 'SYSTEM RUNS WITHOUT YOU (24H)',
    unlockRule: 'No outreach, no reminders, no panic — system still produces output for 24 hours',
    when: 'First system running without effort',
    rewardTitle: 'Do anything offline you choose',
    enjoymentTime: '3 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 79,
    title: 'PASSPORT IN HAND',
    unlockRule: 'Passport physically issued (not just applied)',
    when: 'End of Week 15',
    rewardTitle: 'Watch any full travel vlog or documentary',
    rewardLink: 'https://www.youtube.com/@YesTheory',
    enjoymentTime: '2 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 80,
    title: 'LOCATION INDEPENDENCE DAY',
    unlockRule: 'Work productively from a different city or unfamiliar environment',
    when: 'Day 105 (mental toughness phase)',
    rewardTitle: 'Read: Digital Nomadism',
    rewardLink: 'https://en.wikipedia.org/wiki/Digital_nomad',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 81,
    title: 'SIX-MONTH DISCIPLINE STREAK',
    unlockRule: '180 days with no discipline violations',
    when: 'Start of Week 16',
    rewardTitle: 'Watch anything you want, zero restrictions',
    enjoymentTime: '3 hours (hard cap)',
    phase: 'irreversible-tier',
  },
  {
    id: 82,
    title: 'STARTUP CLEARLY WINS',
    unlockRule: 'Startup metrics dominate cash engine by your own predefined rules',
    when: 'After handling pressure calmly',
    rewardTitle: 'Paul Graham — Default Alive or Default Dead',
    rewardLink: 'https://www.paulgraham.com/aord.html',
    enjoymentTime: '35 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 83,
    title: 'CASH ENGINE AUTOMATED',
    unlockRule: 'One full week where income is generated without manual selling',
    when: 'Mid–Week 16',
    rewardTitle: 'Learn about Passive Income (critically)',
    rewardLink: 'https://en.wikipedia.org/wiki/Passive_income',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 84,
    title: 'FIRST PUBLIC WIN',
    unlockRule: 'Someone publicly acknowledges your work (testimonial, mention, referral)',
    when: 'First execution while emotionally low',
    rewardTitle: 'Watch one long-form interview of a builder you respect',
    enjoymentTime: '1.5 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 85,
    title: 'FIRST LOSS THAT DOESN\'T SHAKE YOU',
    unlockRule: 'Lose money, client, or time — and execute normally the next day',
    when: 'End of Week 16',
    rewardTitle: 'Nassim Taleb — Skin in the Game concept',
    rewardLink: 'https://en.wikipedia.org/wiki/Skin_in_the_Game',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 86,
    title: 'PEERS NOTICE THE GAP',
    unlockRule: 'At least one peer comments on your progress or distance',
    when: 'First result that surprises you',
    rewardTitle: 'Read: Status vs Wealth (Naval)',
    rewardLink: 'https://nav.al/status',
    enjoymentTime: '25 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 87,
    title: 'YOU SAY "NO" TO EASY MONEY',
    unlockRule: 'Reject a tempting but misaligned opportunity',
    when: 'Start of Week 17',
    rewardTitle: 'Opportunity Cost',
    rewardLink: 'https://en.wikipedia.org/wiki/Opportunity_cost',
    enjoymentTime: '25 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 88,
    title: 'LONG-TERM VISION LOCKED',
    unlockRule: 'Write and commit to a 3–5 year plan publicly or irreversibly',
    when: 'After ignoring comfort completely',
    rewardTitle: 'Long-term thinking',
    rewardLink: 'https://en.wikipedia.org/wiki/Long-term_thinking',
    enjoymentTime: '40 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 89,
    title: 'ONE-YEAR SCOREBOARD REVIEW',
    unlockRule: 'Full honest review of the year (numbers, not feelings)',
    when: 'End of Week 17',
    rewardTitle: 'Watch one full reflective documentary or film',
    enjoymentTime: '2.5 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 90,
    title: 'SEASON 3 COMPLETE',
    unlockRule: 'Reach Week 26 with a single dominant focus intact',
    when: 'Day 120 (elite consistency zone)',
    rewardTitle: 'Half-day total disengagement',
    enjoymentTime: '4 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 91,
    title: 'IRREVERSIBILITY MOMENT',
    unlockRule: 'You cannot return to your old routine even if you wanted to',
    when: 'Start of Week 18',
    rewardTitle: 'Read: Path Dependence',
    rewardLink: 'https://en.wikipedia.org/wiki/Path_dependence',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 92,
    title: 'NO-RETURN POINT',
    unlockRule: 'Income + identity now publicly tied to what you\'re building',
    when: 'First confident decision with risk',
    rewardTitle: 'Watch any content you want',
    enjoymentTime: '3 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 93,
    title: 'SILENCE FEELS NORMAL',
    unlockRule: 'One full day without stimulation, panic, or avoidance',
    when: 'Mid–Week 18',
    rewardTitle: 'Silence (intentional)',
    rewardLink: 'https://www.youtube.com/watch?v=JTEFKFiXSx4',
    enjoymentTime: '20 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 94,
    title: 'MONEY FEELS BORING',
    unlockRule: 'Money no longer changes your daily behavior',
    when: 'After executing without checking progress',
    rewardTitle: 'Read: Wealth vs Income',
    rewardLink: 'https://en.wikipedia.org/wiki/Wealth',
    enjoymentTime: '25 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 95,
    title: 'WORK FEELS LIGHT',
    unlockRule: 'Execute hard tasks with low emotional resistance',
    when: 'End of Week 18',
    rewardTitle: 'Watch any long-form creator you enjoy',
    enjoymentTime: '2 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 96,
    title: 'IDENTITY SHIFT CONFIRMED',
    unlockRule: 'Others describe you by what you build, not what you plan',
    when: 'First time people notice change',
    rewardTitle: 'Identity theory',
    rewardLink: 'https://en.wikipedia.org/wiki/Identity_theory',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 97,
    title: 'YOU TRUST YOURSELF',
    unlockRule: 'You keep a hard promise without external pressure',
    when: 'Start of Week 19',
    rewardTitle: 'Self-efficacy',
    rewardLink: 'https://en.wikipedia.org/wiki/Self-efficacy',
    enjoymentTime: '25 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 98,
    title: 'SYSTEM > MOOD (FINAL LOCK)',
    unlockRule: '30 days where execution ignores mood entirely',
    when: 'After choosing discipline over excitement',
    rewardTitle: 'Watch anything, anywhere',
    enjoymentTime: '3 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 99,
    title: 'YEAR NOT WASTED',
    unlockRule: 'Clear proof: income, systems, identity all improved',
    when: 'End of Week 19',
    rewardTitle: 'Full reflective evening',
    enjoymentTime: '3 hours',
    phase: 'irreversible-tier',
  },

  // ========== ELITE TIER - Rewards 100-150 ==========
  {
    id: 100,
    title: 'NEXT GAME UNLOCKED',
    unlockRule: 'You can clearly articulate the next decade, not just next year',
    when: 'Day 135 (execution identity locked)',
    rewardTitle: 'Read: The Long Now Foundation',
    rewardLink: 'https://longnow.org/',
    enjoymentTime: 'Unlimited that day only',
    phase: 'elite-tier',
  },
  {
    id: 101,
    title: 'First Four-Figure Proof',
    unlockRule: 'Earn a cumulative $1,000 USD from the cash engine (tracked, real payments).',
    when: 'Start of Week 20',
    rewardTitle: 'One full afternoon with zero execution pressure. You may go anywhere you feel comfortable.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 102,
    title: 'Founder Travel Signal',
    unlockRule: 'Research and document a real, viable business trip to another country (purpose, cost, contacts).',
    when: 'After first real responsibility taken',
    rewardTitle: 'Watch any full-length business or founder documentary of your choice.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 103,
    title: 'Capital Readiness Gate',
    unlockRule: 'Create a 1-page investor-ready startup brief (problem, solution, traction, ask).',
    when: 'Mid–Week 20',
    rewardTitle: 'One premium long-form interview (top-tier founder or investor).',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 104,
    title: '100 Rejections Badge',
    unlockRule: 'Log 100 cumulative rejections (DMs, walk-ins, calls, or startup outreach).',
    when: 'First week with zero self-doubt logs',
    rewardTitle: 'Evening out in a place that feels "above your current level."',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 105,
    title: 'Consistent Operator',
    unlockRule: '14 consecutive GREEN days (no discipline violations).',
    when: 'End of Week 20',
    rewardTitle: 'Watch two Formula 1 race replays back-to-back.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 106,
    title: 'Authority Positioning',
    unlockRule: 'Publish one public authority asset (case study, breakdown, or teaching post).',
    when: 'After solving a hard problem alone',
    rewardTitle: 'Free-choice YouTube deep dive (non-entertainment algorithm junk excluded).',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 107,
    title: 'First Outsider Validation',
    unlockRule: 'Receive unsolicited positive feedback from a customer or user (documented).',
    when: 'Start of Week 21',
    rewardTitle: 'One evening fully off-grid (no guilt).',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 108,
    title: 'Serious Money Week',
    unlockRule: 'Close two paid deals in the same week.',
    when: 'First calm under pressure moment',
    rewardTitle: 'Go somewhere you normally would not justify going.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 109,
    title: 'Passport Trigger',
    unlockRule: 'Apply for your passport (receipt or confirmation).',
    when: 'End of Week 21',
    rewardTitle: 'Watch one full travel or lifestyle documentary.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 110,
    title: 'Sales System Builder',
    unlockRule: 'Build a repeatable outreach script + follow-up system and use it for 5 days.',
    when: 'Day 150 (mid-year strength checkpoint)',
    rewardTitle: 'Any long-form podcast episode of your choice.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 111,
    title: 'Public Commitment Mark',
    unlockRule: 'Publicly state a clear 90-day business target.',
    when: 'Start of Week 22',
    rewardTitle: 'One premium film (cinema-quality).',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 112,
    title: '$2,500 Milestone',
    unlockRule: 'Reach $2,500 USD total revenue.',
    when: 'After making a hard call fast',
    rewardTitle: 'Half-day freedom window.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 113,
    title: 'Startup User Proof',
    unlockRule: '25 real users OR 25 real conversations (logged).',
    when: 'Mid–Week 22',
    rewardTitle: 'Watch any founder biopic or startup film.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 114,
    title: 'Pitch Mastery',
    unlockRule: 'Deliver 50 live pitches (any format).',
    when: 'First proof of leverage',
    rewardTitle: 'Attend any live or recorded business event/talk.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 115,
    title: 'Operational Calm',
    unlockRule: 'One full week where systems run without emotional volatility.',
    when: 'End of Week 22',
    rewardTitle: 'Solo comfort experience (your choice of location).',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 116,
    title: 'First Delegate',
    unlockRule: 'Successfully delegate one task to another human.',
    when: 'After choosing execution over perfection',
    rewardTitle: 'One premium interview marathon.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 117,
    title: 'Market Respect Signal',
    unlockRule: 'A business asks you for advice or help.',
    when: 'Start of Week 23',
    rewardTitle: 'Evening completely off work.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 118,
    title: 'Cash Engine Stability',
    unlockRule: 'Earn money 3 consecutive weeks without panic changes.',
    when: 'First authority-like behavior noticed',
    rewardTitle: 'One long creative or entertainment session.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 119,
    title: 'International Intent',
    unlockRule: 'Contact 5 foreign businesses or founders for collaboration.',
    when: 'End of Week 23',
    rewardTitle: 'Travel-themed content session.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 120,
    title: '$5,000 Threshold',
    unlockRule: 'Cross $5,000 USD cumulative revenue.',
    when: 'Day 165 (operator mindset phase)',
    rewardTitle: 'Full rest evening + premium content.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 121,
    title: 'Strategic Kill',
    unlockRule: 'Kill one idea or feature decisively and document why.',
    when: 'Start of Week 24',
    rewardTitle: 'Watch one high-intensity documentary or film.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 122,
    title: 'Fundraising Readiness',
    unlockRule: 'Prepare a real pitch deck (10–12 slides).',
    when: 'After leading yourself flawlessly for a week',
    rewardTitle: 'Watch any investor AMA or summit talk.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 123,
    title: 'First External Mentor',
    unlockRule: 'Secure one mentor/advisor conversation.',
    when: 'Mid–Week 24',
    rewardTitle: 'Relaxed social or solo outing.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 124,
    title: '$7,500 Proof',
    unlockRule: 'Reach $7,500 USD revenue.',
    when: 'First time stress feels normal',
    rewardTitle: 'Half-day freedom.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 125,
    title: 'Brand Presence',
    unlockRule: 'Launch a consistent public brand channel (post 7 times).',
    when: 'End of Week 24',
    rewardTitle: 'Any premium creator content.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 126,
    title: 'Founder Endurance',
    unlockRule: '30 days with zero rule violations.',
    when: 'After rejecting comfort instinctively',
    rewardTitle: 'Watch an entire F1 race weekend coverage.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 127,
    title: 'Serious Negotiator',
    unlockRule: 'Close a deal above your previous price ceiling.',
    when: 'Start of Week 25',
    rewardTitle: 'Comfort experience upgrade.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 128,
    title: 'Cross-Border Vision',
    unlockRule: 'Finalize a real international expansion plan.',
    when: 'First real control over time',
    rewardTitle: 'Travel or global business documentary.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 129,
    title: '$10,000 Reality Shift',
    unlockRule: 'Reach $10,000 USD total revenue.',
    when: 'End of Week 25',
    rewardTitle: 'One full day reduced workload.',
    enjoymentTime: '5 hours',
    phase: 'elite-tier',
  },
  {
    id: 130,
    title: 'Founder Reputation',
    unlockRule: 'Be publicly referenced or recommended.',
    when: 'Day 180 (half-year earned)',
    rewardTitle: 'Any long premium media of choice.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 131,
    title: 'First Fund Ask',
    unlockRule: 'Make one real fundraising ask (angel, partner, or institution).',
    when: 'Start of Week 26',
    rewardTitle: 'Evening completely free.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 132,
    title: 'Geographic Expansion',
    unlockRule: 'Serve a client outside your city or country.',
    when: 'After executing without tracking dopamine',
    rewardTitle: 'Travel-inspired relaxation block.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 133,
    title: 'Systemized Freedom',
    unlockRule: 'One week where income is earned with <50% direct effort.',
    when: 'Mid–Week 26',
    rewardTitle: 'Half-day enjoyment window.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 134,
    title: 'Identity Lock',
    unlockRule: 'Clearly documented "This is who I am now" statement.',
    when: 'First sense of inevitability',
    rewardTitle: 'Watch one identity-shaping film.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 135,
    title: '$15,000 Mark',
    unlockRule: 'Cross $15,000 USD revenue.',
    when: 'End of Week 26',
    rewardTitle: 'Premium leisure experience.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 136,
    title: 'Market Authority',
    unlockRule: 'Speak or teach publicly once.',
    when: 'After acting like results are guaranteed',
    rewardTitle: 'Any long-form content.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 137,
    title: 'Operational Leader',
    unlockRule: 'Run a full week as planner, not firefighter.',
    when: 'Start of Week 27',
    rewardTitle: 'Full evening free.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 138,
    title: 'International Booking',
    unlockRule: 'Confirm business travel (ticket or invitation).',
    when: 'First strategic thinking shift',
    rewardTitle: 'Celebration outing.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 139,
    title: '$20,000 Reality',
    unlockRule: 'Reach $20,000 USD total revenue.',
    when: 'End of Week 27',
    rewardTitle: 'Full day decompression.',
    enjoymentTime: '5 hours',
    phase: 'elite-tier',
  },
  {
    id: 140,
    title: 'Funded Signal',
    unlockRule: 'Secure any external capital or grant.',
    when: 'Day 195 (elite calm phase)',
    rewardTitle: 'High-end documentary or film session.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 141,
    title: 'Long-Term Lock-In',
    unlockRule: 'Commit publicly to a 12-month roadmap.',
    when: 'Start of Week 28',
    rewardTitle: 'Any premium experience within bounds.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 142,
    title: 'International Presence',
    unlockRule: 'Physically attend a business event abroad.',
    when: 'After choosing legacy over speed',
    rewardTitle: 'Full rest evening.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 143,
    title: '$25,000 Threshold',
    unlockRule: 'Cross $25,000 USD revenue.',
    when: 'Mid–Week 28',
    rewardTitle: 'Half-day freedom.',
    enjoymentTime: '5 hours',
    phase: 'elite-tier',
  },
  {
    id: 144,
    title: 'Team Builder',
    unlockRule: 'Build a 2–3 person execution team.',
    when: 'First "this is real now" realization',
    rewardTitle: 'Comfort + entertainment block.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 145,
    title: 'Market Leader Signal',
    unlockRule: 'Outperform a known competitor.',
    when: 'End of Week 28',
    rewardTitle: 'Any premium long-form content.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 146,
    title: 'Second Country Expansion',
    unlockRule: 'Operate actively in two countries.',
    when: 'After executing with zero emotional noise',
    rewardTitle: 'Celebration experience.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 147,
    title: '$35,000 Proof',
    unlockRule: 'Reach $35,000 USD revenue.',
    when: 'Start of Week 29',
    rewardTitle: 'Full day light-duty.',
    enjoymentTime: '6 hours',
    phase: 'elite-tier',
  },
  {
    id: 148,
    title: 'Irreversibility Moment',
    unlockRule: 'Business income exceeds survival threshold.',
    when: 'Final pre-scale discipline check',
    rewardTitle: 'Personal choice experience.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 149,
    title: 'Public Recognition',
    unlockRule: 'Media mention, award, or formal recognition.',
    when: 'Day 210 (transition into higher-tier rewards)',
    rewardTitle: 'Premium documentary marathon.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 150,
    title: 'Founder Identity Cemented',
    unlockRule: 'One full quarter executed without system changes.',
    rewardTitle: 'Full evening off.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 151,
    title: 'Escape Velocity',
    unlockRule: 'You no longer question whether this path is real.',
    rewardTitle: 'Entire day lived on your terms.',
    enjoymentTime: '8 hours',
    phase: 'elite-tier',
  },

  // ========== END-OF-YEAR / LEGACY TIER - Rewards 152-200 ==========
  {
    id: 152,
    title: 'Proof to Self',
    unlockRule: 'Written comparison: Start of 2026 vs End of 2026.',
    rewardTitle: 'Watch any life-changing documentary or film.',
    enjoymentTime: '3 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 153,
    title: 'City Flex',
    unlockRule: '$50,000+ total earned OR equivalent traction.',
    rewardTitle: 'Spend a full evening in the best place you can access.',
    enjoymentTime: '4 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 154,
    title: 'Public Closure',
    unlockRule: 'Visit your old school as a visitor, not a student.',
    rewardTitle: 'Walk through freely, on your terms.',
    enjoymentTime: '2 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 155,
    title: 'Family Signal',
    unlockRule: 'Contribute meaningfully to your family financially.',
    rewardTitle: 'Family celebration meal you fund.',
    enjoymentTime: '3 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 156,
    title: 'Identity Purchase',
    unlockRule: 'Income stability proven for 3+ months.',
    rewardTitle: 'Buy one item that symbolizes "I\'m not who I was."',
    enjoymentTime: '1 day (ownership reward)',
    phase: 'end-of-year-legacy',
  },
  {
    id: 157,
    title: 'Founder Environment',
    unlockRule: 'Attend or qualify for a real business event.',
    rewardTitle: 'Full event attendance, no guilt.',
    enjoymentTime: 'Event duration',
    phase: 'end-of-year-legacy',
  },
  {
    id: 158,
    title: 'Freedom Day',
    unlockRule: 'No system violations in final 30 days.',
    rewardTitle: 'Entire day unstructured.',
    enjoymentTime: '10 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 159,
    title: 'Social Upgrade',
    unlockRule: 'New peer group formed (documented).',
    rewardTitle: 'Evening social experience of your choosing.',
    enjoymentTime: '4 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 160,
    title: 'Travel Trigger',
    unlockRule: 'International income OR global users.',
    rewardTitle: 'Book an international trip (real).',
    enjoymentTime: 'Trip planning + anticipation',
    phase: 'end-of-year-legacy',
  },
  {
    id: 161,
    title: 'First Class Mindset',
    unlockRule: 'One deal larger than anything before.',
    rewardTitle: 'Luxury experience within reach (hotel, lounge, service).',
    enjoymentTime: '1 day',
    phase: 'end-of-year-legacy',
  },
  {
    id: 162,
    title: 'Legacy Letter',
    unlockRule: 'Write letter to your 2025 self.',
    rewardTitle: 'Quiet reflection evening.',
    enjoymentTime: '2 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 163,
    title: 'Public Respect',
    unlockRule: 'Be introduced as "founder" or "business owner."',
    rewardTitle: 'Celebration evening.',
    enjoymentTime: '3 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 164,
    title: 'Physical Upgrade',
    unlockRule: 'Maintain physical discipline all year.',
    rewardTitle: 'Wardrobe or appearance upgrade.',
    enjoymentTime: 'Ongoing',
    phase: 'end-of-year-legacy',
  },
  {
    id: 165,
    title: 'Geographic Expansion',
    unlockRule: 'Operate in 2+ cities or countries.',
    rewardTitle: 'Multi-day travel experience.',
    enjoymentTime: 'Trip duration',
    phase: 'end-of-year-legacy',
  },
  {
    id: 166,
    title: 'Dream Purchase Gate',
    unlockRule: 'Financial safety buffer achieved.',
    rewardTitle: 'Begin process toward your dream car.',
    enjoymentTime: 'Planning + ownership anticipation',
    phase: 'end-of-year-legacy',
  },
  {
    id: 167,
    title: 'F1 Pilgrimage',
    unlockRule: 'Major revenue milestone OR sponsorship.',
    rewardTitle: 'Attend a Formula 1 race in person (or lock the plan).',
    enjoymentTime: 'Race weekend',
    phase: 'end-of-year-legacy',
  },
  {
    id: 168,
    title: 'Authority Seat',
    unlockRule: 'Speak, teach, or present publicly.',
    rewardTitle: 'Host or attend a high-level dinner or meetup.',
    enjoymentTime: '3 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 169,
    title: 'Global Taste',
    unlockRule: 'International collaboration executed.',
    rewardTitle: 'Travel to a culture you admire.',
    enjoymentTime: 'Trip duration',
    phase: 'end-of-year-legacy',
  },
  {
    id: 170,
    title: 'Old World Exit',
    unlockRule: 'All 2026 obligations closed cleanly.',
    rewardTitle: 'Delete old identity artifacts.',
    enjoymentTime: 'Psychological release',
    phase: 'end-of-year-legacy',
  },
  {
    id: 171,
    title: 'Personal Flag',
    unlockRule: 'Define your personal symbol or motto.',
    rewardTitle: 'Commission or buy a custom item representing it.',
    enjoymentTime: 'Ongoing',
    phase: 'end-of-year-legacy',
  },
  {
    id: 172,
    title: 'Inner Circle',
    unlockRule: 'Trusted network of 5+ serious people.',
    rewardTitle: 'Private celebration.',
    enjoymentTime: '4 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 173,
    title: 'Confidence Proof',
    unlockRule: 'Walk into any room without shrinking.',
    rewardTitle: 'Evening out purely for enjoyment.',
    enjoymentTime: '3 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 174,
    title: 'Time Ownership',
    unlockRule: 'Income not tied to hours.',
    rewardTitle: 'Entire day doing nothing productive.',
    enjoymentTime: '10 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 175,
    title: 'The Look Back',
    unlockRule: 'Final 2026 review completed.',
    rewardTitle: 'Watch anything you want without rules.',
    enjoymentTime: '4 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 176,
    title: 'Symbolic Departure',
    unlockRule: 'Leave a place tied to struggle.',
    rewardTitle: 'Travel or relocation moment.',
    enjoymentTime: 'Day of transition',
    phase: 'end-of-year-legacy',
  },
  {
    id: 177,
    title: 'Status Confirmation',
    unlockRule: 'Others reference your progress unprompted.',
    rewardTitle: 'High-end experience of choice.',
    enjoymentTime: '1 day',
    phase: 'end-of-year-legacy',
  },
  {
    id: 178,
    title: 'Personal Celebration',
    unlockRule: 'All systems completed.',
    rewardTitle: 'Throw or attend a celebration on your terms.',
    enjoymentTime: 'Event duration',
    phase: 'end-of-year-legacy',
  },
  {
    id: 179,
    title: 'Dream Access',
    unlockRule: 'Reach a place you once thought "not for me."',
    rewardTitle: 'Full experience there.',
    enjoymentTime: 'Visit duration',
    phase: 'end-of-year-legacy',
  },
  {
    id: 180,
    title: 'Identity Lock',
    unlockRule: 'You no longer negotiate with fear.',
    rewardTitle: 'Symbolic ritual or trip.',
    enjoymentTime: '1 day',
    phase: 'end-of-year-legacy',
  },
  {
    id: 181,
    title: 'Future Fund',
    unlockRule: 'Money set aside for 2027 vision.',
    rewardTitle: 'Peace-of-mind evening.',
    enjoymentTime: '3 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 182,
    title: 'Gratitude Reset',
    unlockRule: 'Thank everyone who mattered.',
    rewardTitle: 'Quiet, satisfied night.',
    enjoymentTime: '2 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 183,
    title: 'Independence Proof',
    unlockRule: 'You can walk away and still be fine.',
    rewardTitle: 'Freedom day.',
    enjoymentTime: '8 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 184,
    title: 'Lifestyle Shift',
    unlockRule: 'Daily life upgraded permanently.',
    rewardTitle: 'Live it.',
    enjoymentTime: 'Ongoing',
    phase: 'end-of-year-legacy',
  },
  {
    id: 185,
    title: '"I Made It" Moment',
    unlockRule: 'You feel calm instead of desperate.',
    rewardTitle: 'Sunset or night drive, no destination.',
    enjoymentTime: '2 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 186,
    title: 'Boundary Celebration',
    unlockRule: 'You enforce standards naturally.',
    rewardTitle: 'Luxury solitude.',
    enjoymentTime: '1 day',
    phase: 'end-of-year-legacy',
  },
  {
    id: 187,
    title: 'Vision Lock-In',
    unlockRule: '2027 plan defined.',
    rewardTitle: 'Celebration evening.',
    enjoymentTime: '3 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 188,
    title: 'Final Flex',
    unlockRule: 'Do something old-you couldn\'t afford.',
    rewardTitle: 'Enjoy it fully.',
    enjoymentTime: 'Varies',
    phase: 'end-of-year-legacy',
  },
  {
    id: 189,
    title: 'Closure Visit',
    unlockRule: 'Visit a past struggle location calmly.',
    rewardTitle: 'Leave without emotion.',
    enjoymentTime: '1 hour',
    phase: 'end-of-year-legacy',
  },
  {
    id: 190,
    title: 'Elite Calm',
    unlockRule: 'No urgency left in your system.',
    rewardTitle: 'Day without stimulation.',
    enjoymentTime: '6 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 191,
    title: 'The Thank You',
    unlockRule: 'Acknowledge your own discipline.',
    rewardTitle: 'Private celebration.',
    enjoymentTime: '2 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 192,
    title: 'The Upgrade',
    unlockRule: 'You act before thinking.',
    rewardTitle: 'Permanent lifestyle improvement.',
    enjoymentTime: 'Ongoing',
    phase: 'end-of-year-legacy',
  },
  {
    id: 193,
    title: 'Global Citizen',
    unlockRule: 'Operate internationally with ease.',
    rewardTitle: 'Travel freely.',
    enjoymentTime: 'Trip duration',
    phase: 'end-of-year-legacy',
  },
  {
    id: 194,
    title: 'Peaceful Power',
    unlockRule: 'You stop proving.',
    rewardTitle: 'Quiet night with pride.',
    enjoymentTime: '2 hours',
    phase: 'end-of-year-legacy',
  },
  {
    id: 195,
    title: 'Year Closed',
    unlockRule: 'December 31, 2026 completed cleanly.',
    rewardTitle: 'Night without reflection.',
    enjoymentTime: 'Entire evening',
    phase: 'end-of-year-legacy',
  },
  {
    id: 196,
    title: 'Identity Crown',
    unlockRule: 'You trust yourself fully.',
    rewardTitle: 'Signature experience.',
    enjoymentTime: '1 day',
    phase: 'end-of-year-legacy',
  },
  {
    id: 197,
    title: 'Final Exhale',
    unlockRule: 'System officially ends.',
    rewardTitle: 'Do nothing.',
    enjoymentTime: '1 day',
    phase: 'end-of-year-legacy',
  },
  {
    id: 198,
    title: 'New Era',
    unlockRule: '2027 begins without fear.',
    rewardTitle: 'Fresh start experience.',
    enjoymentTime: '1 day',
    phase: 'end-of-year-legacy',
  },
  {
    id: 199,
    title: 'Legacy Seed',
    unlockRule: 'You think long-term naturally.',
    rewardTitle: 'Invest in something lasting.',
    enjoymentTime: 'Symbolic',
    phase: 'end-of-year-legacy',
  },
  {
    id: 200,
    title: 'Escape Velocity (Baseline Entry)',
    unlockRule: 'Startup or agency sustains income without daily oversight.',
    rewardTitle: 'One full week without operational work.',
    enjoymentTime: '7 days',
    phase: 'end-of-year-legacy',
  },

  // ========== MYTHIC / HIGH-LEVERAGE TIER - Rewards 201-250 ==========
  {
    id: 201,
    title: 'First Real Team',
    unlockRule: 'Hire your first paid team member.',
    rewardTitle: 'Celebrate with a full day off-site.',
    enjoymentTime: '1 day',
    phase: 'mythic-high-leverage',
  },
  {
    id: 202,
    title: 'Founder Circle',
    unlockRule: 'Regularly communicate with founders ahead of you.',
    rewardTitle: 'Attend a high-level mastermind or private event.',
    enjoymentTime: 'Event duration',
    phase: 'mythic-high-leverage',
  },
  {
    id: 203,
    title: 'Six-Figure Proof',
    unlockRule: '$100,000 total revenue crossed.',
    rewardTitle: 'Luxury experience you once thought was "too much."',
    enjoymentTime: '1–2 days',
    phase: 'mythic-high-leverage',
  },
  {
    id: 204,
    title: 'Global Operator',
    unlockRule: 'Customers/users in 3+ countries.',
    rewardTitle: 'International travel for business.',
    enjoymentTime: 'Trip duration',
    phase: 'mythic-high-leverage',
  },
  {
    id: 205,
    title: 'Public Recognition',
    unlockRule: 'Media mention, interview, or feature.',
    rewardTitle: 'Full day of unrestricted enjoyment.',
    enjoymentTime: '1 day',
    phase: 'mythic-high-leverage',
  },
  {
    id: 206,
    title: 'First Acquisition Attempt',
    unlockRule: 'Serious acquisition offer made or received.',
    rewardTitle: 'High-end dinner or experience.',
    enjoymentTime: 'Evening',
    phase: 'mythic-high-leverage',
  },
  {
    id: 207,
    title: 'Founder-Level Network',
    unlockRule: 'Introduced into a private founder group.',
    rewardTitle: 'Travel or event access.',
    enjoymentTime: 'Event duration',
    phase: 'mythic-high-leverage',
  },
  {
    id: 208,
    title: 'Thought Leader',
    unlockRule: 'People quote or reference your ideas publicly.',
    rewardTitle: 'Personal brand investment.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 209,
    title: 'Infrastructure Lock',
    unlockRule: 'Systems run without your presence.',
    rewardTitle: 'Multi-day rest without guilt.',
    enjoymentTime: '3 days',
    phase: 'mythic-high-leverage',
  },
  {
    id: 210,
    title: 'First Property Abroad',
    unlockRule: 'Buy your first property outside your home country.',
    rewardTitle: 'Stay there uninterrupted.',
    enjoymentTime: '1 week',
    phase: 'mythic-high-leverage',
  },
  {
    id: 211,
    title: 'Million-Dollar Trajectory',
    unlockRule: 'Clear path to $1M valuation or revenue.',
    rewardTitle: 'Executive-level experience (retreat, coaching, travel).',
    enjoymentTime: 'Varies',
    phase: 'mythic-high-leverage',
  },
  {
    id: 212,
    title: 'Industry Insider',
    unlockRule: 'Direct access to key players in your industry.',
    rewardTitle: 'Private meetings.',
    enjoymentTime: 'Event duration',
    phase: 'mythic-high-leverage',
  },
  {
    id: 213,
    title: 'Founder Mentorship',
    unlockRule: 'Mentored by someone 10x ahead.',
    rewardTitle: 'One-on-one strategic retreat.',
    enjoymentTime: '1–2 days',
    phase: 'mythic-high-leverage',
  },
  {
    id: 214,
    title: 'Global Residency',
    unlockRule: 'Legal ability to live/work abroad.',
    rewardTitle: 'Choose where you wake up.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 215,
    title: 'Brand Power',
    unlockRule: 'Your name alone opens doors.',
    rewardTitle: 'High-status environment access.',
    enjoymentTime: 'Event duration',
    phase: 'mythic-high-leverage',
  },
  {
    id: 216,
    title: 'Seven-Figure Year',
    unlockRule: '$1,000,000+ in a 12-month period.',
    rewardTitle: 'Signature luxury experience.',
    enjoymentTime: '1 week',
    phase: 'mythic-high-leverage',
  },
  {
    id: 217,
    title: 'Strategic Silence',
    unlockRule: 'You no longer explain yourself.',
    rewardTitle: 'Retreat in isolation or nature.',
    enjoymentTime: '3 days',
    phase: 'mythic-high-leverage',
  },
  {
    id: 218,
    title: 'Global Mobility',
    unlockRule: 'Business operates across borders.',
    rewardTitle: 'Multi-country travel.',
    enjoymentTime: 'Trip duration',
    phase: 'mythic-high-leverage',
  },
  {
    id: 219,
    title: 'Investor Respect',
    unlockRule: 'Investors approach you.',
    rewardTitle: 'Choose who you work with.',
    enjoymentTime: 'Strategic, ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 220,
    title: 'Identity Residence',
    unlockRule: 'Buy or lease a home that reflects your identity.',
    rewardTitle: 'Live there fully present.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 221,
    title: 'Founder Recognition',
    unlockRule: 'Recognized as a serious operator.',
    rewardTitle: 'Attend elite invite-only event.',
    enjoymentTime: 'Event duration',
    phase: 'mythic-high-leverage',
  },
  {
    id: 222,
    title: 'Personal Board',
    unlockRule: 'Advisory board established.',
    rewardTitle: 'Strategic reset retreat.',
    enjoymentTime: '2 days',
    phase: 'mythic-high-leverage',
  },
  {
    id: 223,
    title: 'Platform Power',
    unlockRule: 'Audience >100,000 or equivalent reach.',
    rewardTitle: 'Monetize attention on your terms.',
    enjoymentTime: 'Strategic freedom',
    phase: 'mythic-high-leverage',
  },
  {
    id: 224,
    title: 'Market Leader',
    unlockRule: 'Category dominance in your niche.',
    rewardTitle: 'Celebration travel.',
    enjoymentTime: '1 week',
    phase: 'mythic-high-leverage',
  },
  {
    id: 225,
    title: 'First Exit',
    unlockRule: 'Sell a company or asset.',
    rewardTitle: 'Time-rich lifestyle period.',
    enjoymentTime: '1 month',
    phase: 'mythic-high-leverage',
  },
  {
    id: 226,
    title: 'Founder Freedom',
    unlockRule: 'Income without location dependence.',
    rewardTitle: 'Live anywhere.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 227,
    title: 'Global Influence',
    unlockRule: 'Decisions affect thousands.',
    rewardTitle: 'Influence used intentionally.',
    enjoymentTime: 'Purpose-driven',
    phase: 'mythic-high-leverage',
  },
  {
    id: 228,
    title: 'Personal Legacy Asset',
    unlockRule: 'Create something that outlives you.',
    rewardTitle: 'Long-term pride.',
    enjoymentTime: 'Permanent',
    phase: 'mythic-high-leverage',
  },
  {
    id: 229,
    title: 'Elite Association',
    unlockRule: 'You are invited, not applying.',
    rewardTitle: 'Access elite environments.',
    enjoymentTime: 'Event duration',
    phase: 'mythic-high-leverage',
  },
  {
    id: 230,
    title: 'Cultural Integration',
    unlockRule: 'Operate fluently in multiple cultures.',
    rewardTitle: 'Global lifestyle.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 231,
    title: 'Financial Independence',
    unlockRule: 'Passive income covers living costs.',
    rewardTitle: 'Total time control.',
    enjoymentTime: 'Unlimited',
    phase: 'mythic-high-leverage',
  },
  {
    id: 232,
    title: 'Authority Without Noise',
    unlockRule: 'Respect precedes you.',
    rewardTitle: 'Silent power.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 233,
    title: 'Founder Retreat',
    unlockRule: 'Annual strategic retreat established.',
    rewardTitle: 'Deep reset.',
    enjoymentTime: '1 week',
    phase: 'mythic-high-leverage',
  },
  {
    id: 234,
    title: 'Generational Shift',
    unlockRule: 'Family trajectory permanently changed.',
    rewardTitle: 'Legacy celebration.',
    enjoymentTime: 'Symbolic',
    phase: 'mythic-high-leverage',
  },
  {
    id: 235,
    title: 'Global Citizenship',
    unlockRule: 'Multiple residencies or passports.',
    rewardTitle: 'Borderless living.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 236,
    title: 'Influence Capital',
    unlockRule: 'You can mobilize people/resources.',
    rewardTitle: 'Strategic freedom.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 237,
    title: 'Self-Made Proof',
    unlockRule: 'No external dependency.',
    rewardTitle: 'Deep confidence.',
    enjoymentTime: 'Permanent',
    phase: 'mythic-high-leverage',
  },
  {
    id: 238,
    title: 'Founder Calm',
    unlockRule: 'Pressure no longer disturbs you.',
    rewardTitle: 'Peaceful dominance.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 239,
    title: 'Expansion Phase',
    unlockRule: 'Company expands internationally.',
    rewardTitle: 'Global operations trip.',
    enjoymentTime: 'Trip duration',
    phase: 'mythic-high-leverage',
  },
  {
    id: 240,
    title: 'Legacy Residence',
    unlockRule: 'Home chosen for long-term life.',
    rewardTitle: 'Settle without urgency.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 241,
    title: 'Next-Gen Builder',
    unlockRule: 'You mentor others seriously.',
    rewardTitle: 'Meaningful contribution.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 242,
    title: 'Wealth Without Anxiety',
    unlockRule: 'Money stops influencing decisions.',
    rewardTitle: 'Psychological freedom.',
    enjoymentTime: 'Permanent',
    phase: 'mythic-high-leverage',
  },
  {
    id: 243,
    title: 'Global Respect',
    unlockRule: 'Name recognized across borders.',
    rewardTitle: 'Access anywhere.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 244,
    title: 'Founder Authority',
    unlockRule: 'Your decisions shape markets.',
    rewardTitle: 'Influence responsibly.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 245,
    title: 'Exit Optionality',
    unlockRule: 'You can sell or hold freely.',
    rewardTitle: 'Strategic choice.',
    enjoymentTime: 'Permanent',
    phase: 'mythic-high-leverage',
  },
  {
    id: 246,
    title: 'Iconic Lifestyle',
    unlockRule: 'Life aligned with values.',
    rewardTitle: 'Live intentionally.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 247,
    title: 'Global Base',
    unlockRule: 'Multiple operational bases.',
    rewardTitle: 'Choose location freely.',
    enjoymentTime: 'Ongoing',
    phase: 'mythic-high-leverage',
  },
  {
    id: 248,
    title: 'Wealth With Purpose',
    unlockRule: 'Capital deployed meaningfully.',
    rewardTitle: 'Deep fulfillment.',
    enjoymentTime: 'Permanent',
    phase: 'mythic-high-leverage',
  },
  {
    id: 249,
    title: 'No Return Point',
    unlockRule: 'Old life impossible to return to.',
    rewardTitle: 'Forward-only living.',
    enjoymentTime: 'Permanent',
    phase: 'mythic-high-leverage',
  },
  {
    id: 250,
    title: 'Post-Scarcity Mode',
    unlockRule: 'You act from vision, not fear.',
    rewardTitle: 'Life as creation.',
    enjoymentTime: 'Unlimited',
    phase: 'mythic-high-leverage',
  },
  // ========== SOVEREIGN / HIGH-STATUS OPERATOR TIER (Rewards 251-300) ==========
  {
    id: 251,
    title: 'Authority Posture',
    unlockRule: 'You stop seeking validation unconsciously.',
    rewardTitle: 'Move through public spaces calmly and deliberately.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 252,
    title: 'Strategic Perspective',
    unlockRule: 'Quarterly plans executed without panic.',
    rewardTitle: 'Private strategy day (no execution).',
    enjoymentTime: '6 hours',
    phase: 'sovereign-tier',
  },
  {
    id: 253,
    title: 'Inner Circle Dinner',
    unlockRule: 'Trusted circle of high-quality people exists.',
    rewardTitle: 'Host a private dinner or meeting.',
    enjoymentTime: '3 hours',
    phase: 'sovereign-tier',
  },
  {
    id: 254,
    title: 'Founder\'s Calm',
    unlockRule: 'Problems feel solvable by default.',
    rewardTitle: 'Silent evening without stimulation.',
    enjoymentTime: '2 hours',
    phase: 'sovereign-tier',
  },
  {
    id: 255,
    title: 'Public Contribution',
    unlockRule: 'Share real experience publicly (talk, article, post).',
    rewardTitle: 'Recognition without chasing it.',
    enjoymentTime: 'Psychological',
    phase: 'sovereign-tier',
  },
  {
    id: 256,
    title: 'Decision Speed',
    unlockRule: 'Major decisions made without second-guessing.',
    rewardTitle: 'Clear mental bandwidth.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 257,
    title: 'Capital Steward',
    unlockRule: 'Money managed intentionally, not emotionally.',
    rewardTitle: 'Allocate capital to growth or impact.',
    enjoymentTime: 'Strategic satisfaction',
    phase: 'sovereign-tier',
  },
  {
    id: 258,
    title: 'Influence Responsibility',
    unlockRule: 'Others act based on your direction.',
    rewardTitle: 'Use influence consciously.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 259,
    title: 'Founder Rhythm',
    unlockRule: 'You work in cycles, not sprints.',
    rewardTitle: 'Sustainable daily pace.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 260,
    title: 'Taste Upgrade',
    unlockRule: 'You choose quality over excess.',
    rewardTitle: 'Enjoy refined environments.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 261,
    title: 'Long View Thinking',
    unlockRule: 'Decisions consider 5–10 year effects.',
    rewardTitle: 'Strategic patience.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 262,
    title: 'Mentor Mode',
    unlockRule: 'Guide someone seriously.',
    rewardTitle: 'Fulfillment through transfer of wisdom.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 263,
    title: 'Executive Health',
    unlockRule: 'Health routines are automatic.',
    rewardTitle: 'Physical confidence.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 264,
    title: 'Reputation Shield',
    unlockRule: 'Your word is trusted.',
    rewardTitle: 'Reduced friction everywhere.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 265,
    title: 'Founder Aesthetic',
    unlockRule: 'Your presence feels intentional.',
    rewardTitle: 'Personal style fully aligned.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 266,
    title: 'Strategic Travel',
    unlockRule: 'Travel tied to leverage, not escape.',
    rewardTitle: 'Business or vision trip.',
    enjoymentTime: 'Trip duration',
    phase: 'sovereign-tier',
  },
  {
    id: 267,
    title: 'Silence Power',
    unlockRule: 'You speak less, impact more.',
    rewardTitle: 'Authority without explanation.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 268,
    title: 'Operational Mastery',
    unlockRule: 'You see systems, not tasks.',
    rewardTitle: 'Reduced cognitive load.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 269,
    title: 'Cultural Fluency',
    unlockRule: 'Navigate different worlds comfortably.',
    rewardTitle: 'Social adaptability.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 270,
    title: 'Executive Environment',
    unlockRule: 'Workspace reflects seriousness.',
    rewardTitle: 'Operate in a premium environment.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 271,
    title: 'Legacy Thinking',
    unlockRule: 'You act with responsibility to future self.',
    rewardTitle: 'Deep internal alignment.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 272,
    title: 'Strategic Detachment',
    unlockRule: 'Emotions no longer hijack decisions.',
    rewardTitle: 'Calm leadership.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 273,
    title: 'Wealth Neutrality',
    unlockRule: 'Money stops triggering impulsive behavior.',
    rewardTitle: 'Psychological freedom.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 274,
    title: 'Executive Presence',
    unlockRule: 'You command rooms without effort.',
    rewardTitle: 'Social ease at high levels.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 275,
    title: 'Long-Term Asset',
    unlockRule: 'Own something that compounds for decades.',
    rewardTitle: 'Quiet confidence.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 276,
    title: 'Founder\'s Evening',
    unlockRule: 'Days end without unfinished mental loops.',
    rewardTitle: 'Peaceful nights.',
    enjoymentTime: 'Nightly',
    phase: 'sovereign-tier',
  },
  {
    id: 277,
    title: 'Authority Without Aggression',
    unlockRule: 'Boundaries respected automatically.',
    rewardTitle: 'Effortless control.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 278,
    title: 'Stewardship Mindset',
    unlockRule: 'You protect what you\'ve built.',
    rewardTitle: 'Sustainable growth.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 279,
    title: 'Strategic Generosity',
    unlockRule: 'Give without weakening yourself.',
    rewardTitle: 'Meaningful contribution.',
    enjoymentTime: 'Psychological',
    phase: 'sovereign-tier',
  },
  {
    id: 280,
    title: 'Identity Stability',
    unlockRule: 'No identity swings under pressure.',
    rewardTitle: 'Internal consistency.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 281,
    title: 'Global Operator Calm',
    unlockRule: 'Operate across borders smoothly.',
    rewardTitle: 'Geographic flexibility.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 282,
    title: 'Founder Memory',
    unlockRule: 'Reflect on early struggle without pain.',
    rewardTitle: 'Gratitude.',
    enjoymentTime: '1 hour',
    phase: 'sovereign-tier',
  },
  {
    id: 283,
    title: 'Strategic Distance',
    unlockRule: 'You step back before scaling.',
    rewardTitle: 'Fewer mistakes.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 284,
    title: 'Executive Listening',
    unlockRule: 'You hear what\'s not said.',
    rewardTitle: 'Deeper insight.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 285,
    title: 'Quiet Celebration',
    unlockRule: 'Major milestone achieved without announcement.',
    rewardTitle: 'Private satisfaction.',
    enjoymentTime: 'Evening',
    phase: 'sovereign-tier',
  },
  {
    id: 286,
    title: 'Control of Attention',
    unlockRule: 'No compulsive media use.',
    rewardTitle: 'Mental clarity.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 287,
    title: 'Founder\'s Weekend',
    unlockRule: 'Systems handle operations.',
    rewardTitle: 'Weekend without checking anything.',
    enjoymentTime: '2 days',
    phase: 'sovereign-tier',
  },
  {
    id: 288,
    title: 'Long Horizon Confidence',
    unlockRule: 'You trust your trajectory fully.',
    rewardTitle: 'Calm ambition.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 289,
    title: 'Strategic Withdrawal',
    unlockRule: 'You say no without guilt.',
    rewardTitle: 'Time reclaimed.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 290,
    title: 'Authority Legacy',
    unlockRule: 'Others model your behavior.',
    rewardTitle: 'Respect-based influence.',
    enjoymentTime: 'Ongoing',
    phase: 'sovereign-tier',
  },
  {
    id: 291,
    title: 'End-Year Perspective',
    unlockRule: 'Full review completed honestly.',
    rewardTitle: 'Closure ritual.',
    enjoymentTime: '2 hours',
    phase: 'sovereign-tier',
  },
  {
    id: 292,
    title: 'Identity Integration',
    unlockRule: 'Personal + professional aligned.',
    rewardTitle: 'Inner coherence.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 293,
    title: 'Strategic Reset',
    unlockRule: 'You choose next decade intentionally.',
    rewardTitle: 'Mental reset.',
    enjoymentTime: '1 day',
    phase: 'sovereign-tier',
  },
  {
    id: 294,
    title: 'Founder\'s Gratitude',
    unlockRule: 'Acknowledge your own discipline.',
    rewardTitle: 'Pride without ego.',
    enjoymentTime: '1 hour',
    phase: 'sovereign-tier',
  },
  {
    id: 295,
    title: 'Authority Without Noise',
    unlockRule: 'You no longer broadcast wins.',
    rewardTitle: 'Quiet dominance.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 296,
    title: 'Vision Lock',
    unlockRule: '3–5 year vision finalized.',
    rewardTitle: 'Directional certainty.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 297,
    title: 'Year Seal',
    unlockRule: '2026 closed cleanly.',
    rewardTitle: 'Night of complete peace.',
    enjoymentTime: 'Entire evening',
    phase: 'sovereign-tier',
  },
  {
    id: 298,
    title: 'Founder\'s Silence',
    unlockRule: 'No fear about tomorrow.',
    rewardTitle: 'Deep rest.',
    enjoymentTime: 'Full night',
    phase: 'sovereign-tier',
  },
  {
    id: 299,
    title: 'New Identity',
    unlockRule: 'You no longer identify with struggle.',
    rewardTitle: 'Lightness of being.',
    enjoymentTime: 'Permanent',
    phase: 'sovereign-tier',
  },
  {
    id: 300,
    title: 'Sovereign Mode',
    unlockRule: 'You live by intention, not reaction.',
    rewardTitle: 'Life operated as a long game.',
    enjoymentTime: 'Unlimited',
    phase: 'sovereign-tier',
  },
  // ========== THE FINAL MONTH (Rewards 301-360) ==========
  {
    id: 301,
    title: 'The Final Month Begins',
    unlockRule: 'Entire year system still intact',
    when: 'December 1',
    rewardTitle: 'Slow morning with no pressure',
    enjoymentTime: '2 hours',
    phase: 'final-month',
  },
  {
    id: 302,
    title: 'Clean Desk, Clean Mind',
    unlockRule: 'Workspace reset and simplified',
    when: 'First week of December',
    rewardTitle: 'Workday in a calm, organized space',
    enjoymentTime: 'Full day',
    phase: 'final-month',
  },
  {
    id: 303,
    title: 'First Look Back',
    unlockRule: 'Review January–March honestly',
    when: 'December 2–4',
    rewardTitle: 'Watch one meaningful long-form video/interview',
    enjoymentTime: '1.5 hours',
    phase: 'final-month',
  },
  {
    id: 304,
    title: 'Body Still Strong',
    unlockRule: 'Health discipline maintained till now',
    when: 'Any day after Dec 3',
    rewardTitle: 'Rest evening without guilt',
    enjoymentTime: '2 hours',
    phase: 'final-month',
  },
  {
    id: 305,
    title: 'Quiet Confidence',
    unlockRule: 'No system violations for 14 days',
    when: 'First Sunday of December',
    rewardTitle: 'Solo walk or drive with music',
    enjoymentTime: '1 hour',
    phase: 'final-month',
  },
  {
    id: 306,
    title: 'Money Is Real Now',
    unlockRule: 'You handled real money responsibly this year',
    when: 'Dec 5–7',
    rewardTitle: 'Buy one quality item you delayed all year',
    enjoymentTime: 'Ownership-based',
    phase: 'final-month',
  },
  {
    id: 307,
    title: 'The Mid-Year Mirror',
    unlockRule: 'Review April–August objectively',
    when: 'Dec 6–8',
    rewardTitle: 'Watch a business documentary',
    enjoymentTime: '2 hours',
    phase: 'final-month',
  },
  {
    id: 308,
    title: 'Proof of Discipline',
    unlockRule: 'Porn rule held through December',
    when: 'Any weekday, Week 1',
    rewardTitle: 'Evening with no restrictions',
    enjoymentTime: '2 hours',
    phase: 'final-month',
  },
  {
    id: 309,
    title: 'Environment Upgrade',
    unlockRule: 'Income used intentionally',
    when: 'Dec 8–10',
    rewardTitle: 'Improve room/office setup',
    enjoymentTime: 'Ongoing',
    phase: 'final-month',
  },
  {
    id: 310,
    title: 'Slower Mornings',
    unlockRule: 'System no longer requires panic',
    when: 'Any morning, Week 2',
    rewardTitle: 'Wake without alarm',
    enjoymentTime: 'Morning',
    phase: 'final-month',
  },
  {
    id: 311,
    title: 'First "I Did It"',
    unlockRule: 'You are undeniably ahead of January-you',
    when: 'Dec 10',
    rewardTitle: 'Write one sentence acknowledging it',
    enjoymentTime: '15 minutes (emotional)',
    phase: 'final-month',
  },
  {
    id: 312,
    title: 'Financial Breath',
    unlockRule: 'You survived without borrowing or begging',
    when: 'Dec 10–12',
    rewardTitle: 'Calm night, no money anxiety',
    enjoymentTime: 'Evening',
    phase: 'final-month',
  },
  {
    id: 313,
    title: 'Social Ease',
    unlockRule: 'You no longer feel inferior socially',
    when: 'Any evening, Week 2',
    rewardTitle: 'Casual social time',
    enjoymentTime: '2 hours',
    phase: 'final-month',
  },
  {
    id: 314,
    title: 'The Long Walk',
    unlockRule: '2026 didn\'t break you',
    when: 'Dec 12–14',
    rewardTitle: 'Long reflective walk',
    enjoymentTime: '1–2 hours',
    phase: 'final-month',
  },
  {
    id: 315,
    title: 'Taste Upgrade',
    unlockRule: 'You learned restraint',
    when: 'Week 2',
    rewardTitle: 'Enjoy something refined (food, space, experience)',
    enjoymentTime: '1 hour',
    phase: 'final-month',
  },
  {
    id: 316,
    title: 'Business Closure',
    unlockRule: 'All loose ends documented',
    when: 'Dec 15',
    rewardTitle: 'Close laptop early',
    enjoymentTime: 'Evening off',
    phase: 'final-month',
  },
  {
    id: 317,
    title: 'The Second Look Back',
    unlockRule: 'Review September–November',
    when: 'Dec 15–17',
    rewardTitle: 'Watch one creator you admire',
    enjoymentTime: '1.5 hours',
    phase: 'final-month',
  },
  {
    id: 318,
    title: 'No Rush Day',
    unlockRule: 'Systems handled pressure',
    when: 'Any day, Week 3',
    rewardTitle: 'Work slowly on purpose',
    enjoymentTime: 'Full day',
    phase: 'final-month',
  },
  {
    id: 319,
    title: 'Clean Communications',
    unlockRule: 'You handled conflict maturely this year',
    when: 'Dec 17–18',
    rewardTitle: 'Silent evening',
    enjoymentTime: '2 hours',
    phase: 'final-month',
  },
  {
    id: 320,
    title: 'Identity Purchase',
    unlockRule: 'You earned money cleanly',
    when: 'Dec 18–20',
    rewardTitle: 'Buy something symbolic (watch, jacket, tool)',
    enjoymentTime: 'Ownership-based',
    phase: 'final-month',
  },
  {
    id: 321,
    title: 'First Night of Pride',
    unlockRule: 'You didn\'t quit',
    when: 'Dec 20',
    rewardTitle: 'Night out or night in — your choice',
    enjoymentTime: 'Evening',
    phase: 'final-month',
  },
  {
    id: 322,
    title: 'Family Signal',
    unlockRule: 'You showed responsibility',
    when: 'Dec 20–22',
    rewardTitle: 'Contribute to family in any form',
    enjoymentTime: 'Emotional',
    phase: 'final-month',
  },
  {
    id: 323,
    title: 'The Quiet Smile',
    unlockRule: 'You feel calm remembering January',
    when: 'Any night, Week 3',
    rewardTitle: 'Do nothing, notice the feeling',
    enjoymentTime: '30 minutes',
    phase: 'final-month',
  },
  {
    id: 324,
    title: 'Environment Exit',
    unlockRule: 'Old habits feel foreign',
    when: 'Dec 22–23',
    rewardTitle: 'Remove one old object/app',
    enjoymentTime: 'Instant',
    phase: 'final-month',
  },
  {
    id: 325,
    title: 'Christmas Calm (or equivalent)',
    unlockRule: 'You\'re not behind life',
    when: 'Dec 24–25',
    rewardTitle: 'Enjoy the day fully',
    enjoymentTime: 'Full day',
    phase: 'final-month',
  },
  {
    id: 326,
    title: 'No Comparison',
    unlockRule: 'You stopped measuring against others',
    when: 'Dec 26',
    rewardTitle: 'Peaceful evening',
    enjoymentTime: '2 hours',
    phase: 'final-month',
  },
  {
    id: 327,
    title: 'Yearly Summary',
    unlockRule: 'Write 1-page summary of 2026',
    when: 'Dec 26–27',
    rewardTitle: 'Close the document and rest',
    enjoymentTime: 'Evening',
    phase: 'final-month',
  },
  {
    id: 328,
    title: 'Clean Calendar',
    unlockRule: '2027 not yet planned',
    when: 'Dec 27',
    rewardTitle: 'Empty calendar day',
    enjoymentTime: 'Full day',
    phase: 'final-month',
  },
  {
    id: 329,
    title: 'Body Appreciation',
    unlockRule: 'You respected your health',
    when: 'Dec 27–28',
    rewardTitle: 'Relaxed physical recovery',
    enjoymentTime: '1–2 hours',
    phase: 'final-month',
  },
  {
    id: 330,
    title: 'Digital Silence',
    unlockRule: 'No escape behavior',
    when: 'Dec 28',
    rewardTitle: 'Offline evening',
    enjoymentTime: '3 hours',
    phase: 'final-month',
  },
  {
    id: 331,
    title: 'The Deep Breath',
    unlockRule: 'Nothing urgent left',
    when: 'Dec 29',
    rewardTitle: 'Sit quietly, breathe, acknowledge',
    enjoymentTime: '20 minutes',
    phase: 'final-month',
  },
  {
    id: 332,
    title: 'Memory Lock',
    unlockRule: 'Choose one memory from 2026',
    when: 'Dec 29',
    rewardTitle: 'Let it stay',
    enjoymentTime: 'Emotional',
    phase: 'final-month',
  },
  {
    id: 333,
    title: 'The Last Review',
    unlockRule: 'Honest, no ego review',
    when: 'Dec 30 (Morning)',
    rewardTitle: 'Afternoon off',
    enjoymentTime: 'Half day',
    phase: 'final-month',
  },
  {
    id: 334,
    title: 'Clean Night',
    unlockRule: 'No regrets left unsaid',
    when: 'Dec 30 (Night)',
    rewardTitle: 'Sleep early, peacefully',
    enjoymentTime: 'Night',
    phase: 'final-month',
  },
  {
    id: 335,
    title: 'Year Closing Ritual',
    unlockRule: 'You stayed conscious all year',
    when: 'Dec 31 (Morning)',
    rewardTitle: 'Personal ritual (walk, writing, silence)',
    enjoymentTime: '1 hour',
    phase: 'final-month',
  },
  {
    id: 336,
    title: 'The Final Vault Door',
    unlockRule: 'You are not the same person',
    when: 'Dec 31 (Afternoon)',
    rewardTitle: 'Open the entire vault list and read it',
    enjoymentTime: '30 minutes',
    phase: 'final-month',
  },
  {
    id: 337,
    title: 'Proof Moment',
    unlockRule: 'You feel it internally',
    when: 'Dec 31 (Sunset)',
    rewardTitle: 'Watch the sunset intentionally',
    enjoymentTime: '20 minutes',
    phase: 'final-month',
  },
  {
    id: 338,
    title: 'Night of Arrival',
    unlockRule: 'Year closed clean',
    when: 'Dec 31 (Night)',
    rewardTitle: 'Celebrate in your preferred way',
    enjoymentTime: 'Evening',
    phase: 'final-month',
  },
  {
    id: 339,
    title: 'No Fear for Tomorrow',
    unlockRule: 'You trust yourself now',
    when: 'Midnight',
    rewardTitle: 'Deep calm',
    enjoymentTime: 'Internal',
    phase: 'final-month',
  },
  {
    id: 340,
    title: 'First Step of 2027',
    unlockRule: 'Wake without anxiety',
    when: 'Jan 1 (Early Morning)',
    rewardTitle: 'Quiet start to the year',
    enjoymentTime: 'Morning',
    phase: 'final-month',
  },
  {
    id: 341,
    title: 'Identity Lock-In',
    unlockRule: 'You know who you are now',
    when: 'Jan 1',
    rewardTitle: 'Carry that identity forward',
    enjoymentTime: 'Permanent',
    phase: 'final-month',
  },
  {
    id: 360,
    title: 'The Statement',
    unlockRule: 'Someone asks "how did you do it?"',
    when: 'Any day after Jan 1',
    rewardTitle: 'You smile — and answer calmly',
    enjoymentTime: 'Lifetime',
    phase: 'final-month',
  },
];

export function getRewardsByPhase(phase: VaultReward['phase']): VaultReward[] {
  return VAULT_REWARDS.filter(r => r.phase === phase);
}

export function getPhaseOrder(): VaultReward['phase'][] {
  return ['ignition', 'pressure-signal', 'proof-escalation', 'consolidation-signal', 'leverage-selection', 'irreversible-tier', 'elite-tier', 'end-of-year-legacy', 'mythic-high-leverage', 'sovereign-tier', 'final-month'];
}
