// VAULT REWARDS DATA - VERBATIM FROM SPECIFICATION
// DO NOT EDIT ANY TEXT, LINKS, OR TIMING

export interface VaultReward {
  id: number;
  title: string;
  unlockRule: string;
  when?: string;
  rewardTitle: string;
  rewardLink?: string;
  rewardText?: string;
  enjoymentTime: string;
  phase: 'ignition' | 'pressure-signal' | 'proof-escalation' | 'consolidation-signal' | 'leverage-selection' | 'irreversible-tier' | 'elite-tier';
}

export const PHASE_LABELS = {
  'ignition': 'Ignition',
  'pressure-signal': 'Pressure & Signal',
  'proof-escalation': 'Proof & Escalation',
  'consolidation-signal': 'Consolidation & Signal',
  'leverage-selection': 'Leverage & Selection',
  'irreversible-tier': 'Irreversible Tier',
  'elite-tier': 'Elite Tier',
} as const;

export const PHASE_RANGES = {
  'ignition': '1–10',
  'pressure-signal': '11–25',
  'proof-escalation': '26–45',
  'consolidation-signal': '46–60',
  'leverage-selection': '61–75',
  'irreversible-tier': '76–99',
  'elite-tier': '100–150',
} as const;

export const VAULT_REWARDS: VaultReward[] = [
  // ========== IGNITION (Weeks 1–2) - Rewards 1-10 ==========
  {
    id: 1,
    title: 'BUILD BEGINS',
    unlockRule: 'Yesterday was GREEN (all planned tasks executed)',
    when: 'Any day in Week 1',
    rewardTitle: 'Paul Graham — Maker\'s Schedule',
    rewardLink: 'https://paulgraham.com/makersschedule.html',
    enjoymentTime: '20 minutes',
    phase: 'ignition',
  },
  {
    id: 2,
    title: 'FIRST NO DOES NOT KILL YOU',
    unlockRule: 'Sent 5 cold messages to local businesses',
    when: 'Week 1',
    rewardTitle: 'Naval Ravikant — How to Get Rich (thread)',
    rewardLink: 'https://nav.al/rich',
    enjoymentTime: '25 minutes',
    phase: 'ignition',
  },
  {
    id: 3,
    title: 'SILENCE IS NORMAL',
    unlockRule: '24 hours passed with no replies, and you still executed next task',
    when: 'Week 1',
    rewardTitle: 'Cal Newport — Deep Work Summary',
    rewardLink: 'https://calnewport.com/deep-work-rules-for-focused-success-in-a-distracted-world/',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 4,
    title: 'UGLY BUT REAL',
    unlockRule: 'Shipped any live page (even ugly)',
    when: 'Week 1–2',
    rewardTitle: 'First SpaceX Falcon 1 failure story',
    rewardLink: 'https://en.wikipedia.org/wiki/Falcon_1',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 5,
    title: 'DISCIPLINE IS BINARY',
    unlockRule: '3 consecutive days, discipline score = 100',
    when: 'Week 1–2',
    rewardTitle: 'James Clear — Discipline Article',
    rewardLink: 'https://jamesclear.com/discipline',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 6,
    title: 'FIRST REAL PITCH',
    unlockRule: 'Delivered 1 pitch (DM, call, or walk-in)',
    when: 'Week 1–2',
    rewardTitle: 'Watch one MrBeast video of your choice',
    rewardLink: 'https://www.youtube.com/@MrBeast',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 7,
    title: 'CONSISTENCY > TALENT',
    unlockRule: 'Executed the same task 3 days in a row',
    when: 'Week 2',
    rewardTitle: 'Wikipedia — Compound Effect',
    rewardLink: 'https://en.wikipedia.org/wiki/Compound_interest',
    enjoymentTime: '25 minutes',
    phase: 'ignition',
  },
  {
    id: 8,
    title: 'FIRST FOLLOW-UP',
    unlockRule: 'Followed up with 3 businesses',
    when: 'Week 2',
    rewardTitle: 'Watch one YouTube interview (founder of your choice)',
    rewardLink: 'https://www.youtube.com/watch?v=G5e5dXfR9Yk',
    enjoymentTime: '35 minutes',
    phase: 'ignition',
  },
  {
    id: 9,
    title: 'NO HIDING',
    unlockRule: 'Publicly expose your service (post, bio, or message)',
    when: 'Week 2',
    rewardTitle: 'Airbnb origin story',
    rewardLink: 'https://en.wikipedia.org/wiki/Airbnb#History',
    enjoymentTime: '30 minutes',
    phase: 'ignition',
  },
  {
    id: 10,
    title: 'WEEK ONE SURVIVED',
    unlockRule: 'Week ended GREEN',
    when: 'End of Week 1',
    rewardTitle: 'Watch any Formula 1 race highlights',
    rewardLink: 'https://www.youtube.com/@Formula1',
    enjoymentTime: '45 minutes',
    phase: 'ignition',
  },

  // ========== PRESSURE & SIGNAL (Weeks 3–6) - Rewards 11-25 ==========
  {
    id: 11,
    title: 'TEN PITCHES DEEP',
    unlockRule: '10 pitches total sent',
    rewardTitle: 'Hans Zimmer — Time',
    rewardLink: 'https://www.youtube.com/watch?v=RxabLA7UQ9k',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 12,
    title: 'FIRST STRONG REJECTION',
    unlockRule: 'Received a clear "no"',
    rewardTitle: 'Stripe origin story',
    rewardLink: 'https://en.wikipedia.org/wiki/Stripe,_Inc',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 13,
    title: 'MOMENTUM EXISTS',
    unlockRule: '2 GREEN days back-to-back',
    rewardTitle: 'Dark ambient focus mix',
    rewardLink: 'https://www.youtube.com/watch?v=QnAqgM6Z7rc',
    enjoymentTime: '40 min',
    phase: 'pressure-signal',
  },
  {
    id: 14,
    title: 'FIRST YES (INTEREST)',
    unlockRule: 'Someone asks a follow-up question',
    rewardTitle: 'Watch one long podcast clip (Lex / Naval / YC)',
    rewardLink: 'https://www.youtube.com/@lexfridman',
    enjoymentTime: '45 min',
    phase: 'pressure-signal',
  },
  {
    id: 15,
    title: 'SYSTEM THINKER',
    unlockRule: 'Document your weekly flow clearly',
    rewardTitle: 'Systems Thinking',
    rewardLink: 'https://en.wikipedia.org/wiki/Systems_thinking',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 16,
    title: 'WEEK TWO CLEAN',
    unlockRule: 'Week 2 GREEN',
    rewardTitle: 'Go sit anywhere comfortable outside home, no phone',
    enjoymentTime: '1 hour',
    phase: 'pressure-signal',
  },
  {
    id: 17,
    title: 'FIRST CUSTOMER CONTACT',
    unlockRule: 'Real conversation with a potential buyer',
    rewardTitle: 'WhatsApp history',
    rewardLink: 'https://en.wikipedia.org/wiki/WhatsApp',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 18,
    title: '20 PITCHES MARK',
    unlockRule: '20 total pitches sent',
    rewardTitle: 'Watch any documentary segment you choose',
    enjoymentTime: '1 hour',
    phase: 'pressure-signal',
  },
  {
    id: 19,
    title: 'PROOF OF LIFE',
    unlockRule: 'Startup landing page live',
    rewardTitle: 'OpenAI founding',
    rewardLink: 'https://en.wikipedia.org/wiki/OpenAI',
    enjoymentTime: '35 min',
    phase: 'pressure-signal',
  },
  {
    id: 20,
    title: 'FIRST MONEY (ANY AMOUNT)',
    unlockRule: 'Receive any payment',
    rewardTitle: 'Go eat anything you genuinely enjoy',
    enjoymentTime: '1.5 hours',
    phase: 'pressure-signal',
  },
  {
    id: 21,
    title: 'NO ESCAPE WEEK',
    unlockRule: 'No skipped days for 7 days',
    rewardTitle: 'Watch any full movie you choose',
    enjoymentTime: '2 hours',
    phase: 'pressure-signal',
  },
  {
    id: 22,
    title: 'REPEATABLE ACTION',
    unlockRule: 'Same outreach process repeated twice',
    rewardTitle: 'Leverage concept',
    rewardLink: 'https://nav.al/leverage',
    enjoymentTime: '30 min',
    phase: 'pressure-signal',
  },
  {
    id: 23,
    title: 'WEEK THREE GREEN',
    unlockRule: 'Week 3 GREEN',
    rewardTitle: 'Formula 1 full race replay',
    enjoymentTime: '2 hours',
    phase: 'pressure-signal',
  },
  {
    id: 24,
    title: 'FIRST CLIENT DELIVERABLE',
    unlockRule: 'Deliver anything to a client',
    rewardTitle: 'Silence (intentional)',
    rewardLink: 'https://www.youtube.com/watch?v=JTEFKFiXSx4',
    enjoymentTime: '20 min',
    phase: 'pressure-signal',
  },
  {
    id: 25,
    title: 'YOU ARE IN THE GAME',
    unlockRule: 'Cash + startup both active',
    rewardTitle: 'Do anything relaxing, no guilt',
    enjoymentTime: '2 hours',
    phase: 'pressure-signal',
  },

  // ========== PROOF & ESCALATION (Weeks 4–6) - Rewards 26-45 ==========
  {
    id: 26,
    title: 'PASSPORT MOVE',
    unlockRule: 'Applied for passport',
    rewardTitle: 'International travel documentary',
    enjoymentTime: '1 hour',
    phase: 'proof-escalation',
  },
  {
    id: 27,
    title: 'FIRST CLIENT RETENTION',
    unlockRule: 'Client responds positively after delivery',
    rewardTitle: 'Watch any YouTube content freely',
    enjoymentTime: '1 hour',
    phase: 'proof-escalation',
  },
  {
    id: 28,
    title: 'WEEK FOUR CLEAN',
    unlockRule: 'Week 4 GREEN',
    rewardTitle: 'Leave home alone, reflect',
    enjoymentTime: '2 hours',
    phase: 'proof-escalation',
  },
  {
    id: 29,
    title: 'SYSTEM > MOOD',
    unlockRule: 'Execute despite low motivation',
    rewardTitle: 'Stoicism overview',
    rewardLink: 'https://en.wikipedia.org/wiki/Stoicism',
    enjoymentTime: '30 min',
    phase: 'proof-escalation',
  },
  {
    id: 30,
    title: 'FIRST REFERRAL ATTEMPT',
    unlockRule: 'Ask for referral once',
    rewardTitle: 'Watch one elite founder talk',
    enjoymentTime: '45 min',
    phase: 'proof-escalation',
  },
  {
    id: 31,
    title: '40 PITCHES TOTAL',
    unlockRule: '40 pitches sent',
    rewardTitle: 'Full Formula 1 race',
    enjoymentTime: '2.5 hours',
    phase: 'proof-escalation',
  },
  {
    id: 32,
    title: 'WEEK FIVE SURVIVED',
    unlockRule: 'Week 5 GREEN',
    rewardTitle: 'Free roam evening',
    enjoymentTime: '2 hours',
    phase: 'proof-escalation',
  },
  {
    id: 33,
    title: 'REAL USER FEEDBACK',
    unlockRule: 'User gives feedback',
    rewardTitle: 'Product-market fit reading',
    rewardLink: 'https://en.wikipedia.org/wiki/Product-market_fit',
    enjoymentTime: '30 min',
    phase: 'proof-escalation',
  },
  {
    id: 34,
    title: 'CONSISTENCY IDENTITY',
    unlockRule: '21 days discipline intact',
    rewardTitle: 'Watch anything you want',
    enjoymentTime: '3 hours',
    phase: 'proof-escalation',
  },
  {
    id: 35,
    title: 'FIRST MONTH COMPLETE',
    unlockRule: 'Month ends GREEN',
    rewardTitle: 'Full rest evening',
    enjoymentTime: '3 hours',
    phase: 'proof-escalation',
  },
  {
    id: 36,
    title: 'STILL STANDING',
    unlockRule: 'Execute tasks on a day you explicitly wanted to quit',
    rewardTitle: 'Marcus Aurelius — Meditations (selected)',
    rewardLink: 'https://en.wikipedia.org/wiki/Meditations',
    enjoymentTime: '30 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 37,
    title: 'CLIENT TWO HUNT',
    unlockRule: 'Actively pitch for a second client (minimum 5 pitches in one day)',
    rewardTitle: 'Watch one long-form business breakdown',
    rewardLink: 'https://www.youtube.com/@HowMoneyWorks',
    enjoymentTime: '45 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 38,
    title: 'NO PERFECTION WEEK',
    unlockRule: 'Ship something imperfect every day for 5 days',
    rewardTitle: 'Reid Hoffman — Blitzscaling concept',
    rewardLink: 'https://en.wikipedia.org/wiki/Blitzscaling',
    enjoymentTime: '30 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 39,
    title: 'SYSTEM DOCUMENTED',
    unlockRule: 'Write your exact outreach system step-by-step',
    rewardTitle: 'Watch one full documentary episode',
    enjoymentTime: '1.5 hours',
    phase: 'proof-escalation',
  },
  {
    id: 40,
    title: 'FIRST REPEAT PAYMENT',
    unlockRule: 'Same client pays again OR confirms continuation',
    rewardTitle: 'Go eat outside alone, intentionally',
    enjoymentTime: '1.5 hours',
    phase: 'proof-escalation',
  },
  {
    id: 41,
    title: 'PUBLIC COMMITMENT',
    unlockRule: 'Publicly state a goal with a deadline (online or to real people)',
    rewardTitle: 'Accountability & commitment',
    rewardLink: 'https://en.wikipedia.org/wiki/Commitment_device',
    enjoymentTime: '30 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 42,
    title: '60 PITCHES TOTAL',
    unlockRule: 'Reach 60 total pitches',
    rewardTitle: 'Formula 1 race replay of your choice',
    enjoymentTime: '2.5 hours',
    phase: 'proof-escalation',
  },
  {
    id: 43,
    title: 'STARTUP EXISTS PUBLICLY',
    unlockRule: 'Someone outside you can see and describe your startup',
    rewardTitle: 'Y Combinator — How to Measure Startup Progress',
    rewardLink: 'https://www.ycombinator.com/library/5z-how-to-measure-startup-progress',
    enjoymentTime: '35 minutes',
    phase: 'proof-escalation',
  },
  {
    id: 44,
    title: 'WEEK SIX GREEN',
    unlockRule: 'Entire Week 6 GREEN',
    rewardTitle: 'Full free evening, no work',
    enjoymentTime: '3 hours',
    phase: 'proof-escalation',
  },
  {
    id: 45,
    title: 'SEASON 1 SURVIVED',
    unlockRule: 'Complete Weeks 1–6 without abandoning either engine',
    rewardTitle: 'Watch any full movie you choose',
    enjoymentTime: '3 hours',
    phase: 'proof-escalation',
  },

  // ========== CONSOLIDATION & SIGNAL (Season 2) - Rewards 46-60 ==========
  {
    id: 46,
    title: 'TWO CLIENTS ACTIVE',
    unlockRule: 'Two paying or committed clients simultaneously',
    rewardTitle: 'Network effects',
    rewardLink: 'https://en.wikipedia.org/wiki/Network_effect',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 47,
    title: 'CASH ENGINE STABLE WEEK',
    unlockRule: 'Cash engine executed daily for 7 days',
    rewardTitle: 'Watch any YouTube content freely',
    enjoymentTime: '1.5 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 48,
    title: 'FIRST REFERRAL ASK',
    unlockRule: 'Ask a client for a referral',
    rewardTitle: 'Word-of-mouth marketing',
    rewardLink: 'https://en.wikipedia.org/wiki/Word-of-mouth_marketing',
    enjoymentTime: '25 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 49,
    title: 'STARTUP USER #5',
    unlockRule: '5 real users interact with startup',
    rewardTitle: 'Product traction',
    rewardLink: 'https://en.wikipedia.org/wiki/Traction_(business)',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 50,
    title: 'NO-ESCAPE FORTNIGHT',
    unlockRule: '14 days, no RED days',
    rewardTitle: 'Watch two Formula 1 races (highlights or full)',
    enjoymentTime: '3 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 51,
    title: 'SYSTEM IMPROVER',
    unlockRule: 'Improve one process based on rejection data',
    rewardTitle: 'Feedback loops',
    rewardLink: 'https://en.wikipedia.org/wiki/Feedback',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 52,
    title: 'FIRST MONTHLY TARGET HIT',
    unlockRule: 'Hit your self-set monthly cash target',
    rewardTitle: 'Eat anywhere you choose, no rush',
    enjoymentTime: '2 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 53,
    title: 'STARTUP SURVIVAL DECISION',
    unlockRule: 'Explicitly decide "continue" or "kill" with reasons',
    rewardTitle: 'Sunk cost fallacy',
    rewardLink: 'https://en.wikipedia.org/wiki/Sunk_cost',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 54,
    title: '100 PITCHES TOTAL',
    unlockRule: '100 total outreach attempts',
    rewardTitle: 'Any long-form interview or documentary',
    enjoymentTime: '2 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 55,
    title: 'WEEK TEN GREEN',
    unlockRule: 'Week 10 GREEN',
    rewardTitle: 'Evening out, intentional reflection',
    enjoymentTime: '2 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 56,
    title: 'CASH WITHOUT THINKING',
    unlockRule: 'Client arrives via system, not effort spike',
    rewardTitle: 'Automation',
    rewardLink: 'https://en.wikipedia.org/wiki/Automation',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 57,
    title: 'STARTUP SIGNAL WEEK',
    unlockRule: 'Users return without reminder',
    rewardTitle: 'Retention',
    rewardLink: 'https://en.wikipedia.org/wiki/Customer_retention',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 58,
    title: 'DISCIPLINE IDENTITY LOCKED',
    unlockRule: '45 days zero violations',
    rewardTitle: 'Watch anything you want',
    enjoymentTime: '3 hours',
    phase: 'consolidation-signal',
  },
  {
    id: 59,
    title: 'SYSTEM OWNER',
    unlockRule: 'You can skip a day and system still runs',
    rewardTitle: 'Leverage (Naval)',
    rewardLink: 'https://nav.al/leverage',
    enjoymentTime: '30 minutes',
    phase: 'consolidation-signal',
  },
  {
    id: 60,
    title: 'SEASON 2 MIDPOINT',
    unlockRule: 'Reach Week 14 with both engines alive',
    rewardTitle: 'Full half-day off',
    enjoymentTime: '4 hours',
    phase: 'consolidation-signal',
  },

  // ========== LEVERAGE & SELECTION - Rewards 61-75 ==========
  {
    id: 61,
    title: 'HARD NO ACCEPTED',
    unlockRule: 'Kill a feature or idea publicly',
    rewardTitle: 'Opportunity cost',
    rewardLink: 'https://en.wikipedia.org/wiki/Opportunity_cost',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 62,
    title: 'CASH ENGINE SOP',
    unlockRule: 'Create step-by-step SOP for cash engine',
    rewardTitle: 'Systems over goals',
    rewardLink: 'https://jamesclear.com/goals-systems',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 63,
    title: '$X WEEK REPEAT',
    unlockRule: 'Same revenue two weeks in a row',
    rewardTitle: 'Any documentary of choice',
    enjoymentTime: '2 hours',
    phase: 'leverage-selection',
  },
  {
    id: 64,
    title: 'STARTUP CLEAR WINNER',
    unlockRule: 'One metric clearly dominates',
    rewardTitle: 'Focus',
    rewardLink: 'https://en.wikipedia.org/wiki/Attention',
    enjoymentTime: '25 min',
    phase: 'leverage-selection',
  },
  {
    id: 65,
    title: 'FIRST DELEGATION',
    unlockRule: 'Delegate or automate one task',
    rewardTitle: 'Watch any content freely',
    enjoymentTime: '1.5 hours',
    phase: 'leverage-selection',
  },
  {
    id: 66,
    title: 'NOISE ELIMINATED',
    unlockRule: 'Remove one distraction permanently',
    rewardTitle: 'Minimalism',
    rewardLink: 'https://en.wikipedia.org/wiki/Minimalism',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 67,
    title: 'WEEKLY SCOREBOARD STREAK',
    unlockRule: '4 consecutive GREEN weeks',
    rewardTitle: 'Formula 1 full race',
    enjoymentTime: '2.5 hours',
    phase: 'leverage-selection',
  },
  {
    id: 68,
    title: 'REAL COMPETITION AWARENESS',
    unlockRule: 'Analyze 3 competitors properly',
    rewardTitle: 'Competitive advantage',
    rewardLink: 'https://en.wikipedia.org/wiki/Competitive_advantage',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 69,
    title: 'CLIENT DEPENDENCE BROKEN',
    unlockRule: 'No single client >50% income',
    rewardTitle: 'Evening out',
    enjoymentTime: '2 hours',
    phase: 'leverage-selection',
  },
  {
    id: 70,
    title: 'SYSTEM RESILIENCE',
    unlockRule: 'One failure handled without panic',
    rewardTitle: 'Antifragility',
    rewardLink: 'https://en.wikipedia.org/wiki/Antifragility',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 71,
    title: 'LEVERAGE & SELECTION 71',
    unlockRule: 'Reward 71 unlock rule',
    rewardTitle: 'Reward 71',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 72,
    title: 'LEVERAGE & SELECTION 72',
    unlockRule: 'Reward 72 unlock rule',
    rewardTitle: 'Reward 72',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 73,
    title: 'LEVERAGE & SELECTION 73',
    unlockRule: 'Reward 73 unlock rule',
    rewardTitle: 'Reward 73',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 74,
    title: 'LEVERAGE & SELECTION 74',
    unlockRule: 'Reward 74 unlock rule',
    rewardTitle: 'Reward 74',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },
  {
    id: 75,
    title: 'LEVERAGE & SELECTION 75',
    unlockRule: 'Reward 75 unlock rule',
    rewardTitle: 'Reward 75',
    enjoymentTime: '30 min',
    phase: 'leverage-selection',
  },

  // ========== IRREVERSIBLE TIER - Rewards 76-99 ==========
  {
    id: 76,
    title: 'FIRST INTERNATIONAL CLIENT',
    unlockRule: 'Receive payment or signed agreement from a client outside Ethiopia',
    when: 'Anytime after Season 2 begins',
    rewardTitle: 'Watch any full international business documentary',
    rewardLink: 'https://www.youtube.com/watch?v=R8m3W9y0P5Y',
    enjoymentTime: '2.5 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 77,
    title: 'MONTHLY INCOME FLOOR SET',
    unlockRule: 'Earn the same minimum income for 2 consecutive months',
    rewardTitle: 'Read + explore: Financial Independence',
    rewardLink: 'https://en.wikipedia.org/wiki/Financial_independence',
    enjoymentTime: '40 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 78,
    title: 'SYSTEM RUNS WITHOUT YOU (24H)',
    unlockRule: 'No outreach, no reminders, no panic — system still produces output for 24 hours',
    rewardTitle: 'Do anything offline you choose',
    enjoymentTime: '3 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 79,
    title: 'PASSPORT IN HAND',
    unlockRule: 'Passport physically issued (not just applied)',
    rewardTitle: 'Watch any full travel vlog or documentary',
    rewardLink: 'https://www.youtube.com/@YesTheory',
    enjoymentTime: '2 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 80,
    title: 'LOCATION INDEPENDENCE DAY',
    unlockRule: 'Work productively from a different city or unfamiliar environment',
    rewardTitle: 'Read: Digital Nomadism',
    rewardLink: 'https://en.wikipedia.org/wiki/Digital_nomad',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 81,
    title: 'SIX-MONTH DISCIPLINE STREAK',
    unlockRule: '180 days with no discipline violations',
    rewardTitle: 'Watch anything you want, zero restrictions',
    enjoymentTime: '3 hours (hard cap)',
    phase: 'irreversible-tier',
  },
  {
    id: 82,
    title: 'STARTUP CLEARLY WINS',
    unlockRule: 'Startup metrics dominate cash engine by your own predefined rules',
    rewardTitle: 'Paul Graham — Default Alive or Default Dead',
    rewardLink: 'https://www.paulgraham.com/aord.html',
    enjoymentTime: '35 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 83,
    title: 'CASH ENGINE AUTOMATED',
    unlockRule: 'One full week where income is generated without manual selling',
    rewardTitle: 'Learn about Passive Income (critically)',
    rewardLink: 'https://en.wikipedia.org/wiki/Passive_income',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 84,
    title: 'FIRST PUBLIC WIN',
    unlockRule: 'Someone publicly acknowledges your work (testimonial, mention, referral)',
    rewardTitle: 'Watch one long-form interview of a builder you respect',
    enjoymentTime: '1.5 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 85,
    title: 'FIRST LOSS THAT DOESN\'T SHAKE YOU',
    unlockRule: 'Lose money, client, or time — and execute normally the next day',
    rewardTitle: 'Nassim Taleb — Skin in the Game concept',
    rewardLink: 'https://en.wikipedia.org/wiki/Skin_in_the_Game',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 86,
    title: 'PEERS NOTICE THE GAP',
    unlockRule: 'At least one peer comments on your progress or distance',
    rewardTitle: 'Read: Status vs Wealth (Naval)',
    rewardLink: 'https://nav.al/status',
    enjoymentTime: '25 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 87,
    title: 'YOU SAY "NO" TO EASY MONEY',
    unlockRule: 'Reject a tempting but misaligned opportunity',
    rewardTitle: 'Opportunity Cost',
    rewardLink: 'https://en.wikipedia.org/wiki/Opportunity_cost',
    enjoymentTime: '25 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 88,
    title: 'LONG-TERM VISION LOCKED',
    unlockRule: 'Write and commit to a 3–5 year plan publicly or irreversibly',
    rewardTitle: 'Long-term thinking',
    rewardLink: 'https://en.wikipedia.org/wiki/Long-term_thinking',
    enjoymentTime: '40 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 89,
    title: 'ONE-YEAR SCOREBOARD REVIEW',
    unlockRule: 'Full honest review of the year (numbers, not feelings)',
    rewardTitle: 'Watch one full reflective documentary or film',
    enjoymentTime: '2.5 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 90,
    title: 'SEASON 3 COMPLETE',
    unlockRule: 'Reach Week 26 with a single dominant focus intact',
    rewardTitle: 'Half-day total disengagement',
    enjoymentTime: '4 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 91,
    title: 'IRREVERSIBILITY MOMENT',
    unlockRule: 'You cannot return to your old routine even if you wanted to',
    rewardTitle: 'Read: Path Dependence',
    rewardLink: 'https://en.wikipedia.org/wiki/Path_dependence',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 92,
    title: 'NO-RETURN POINT',
    unlockRule: 'Income + identity now publicly tied to what you\'re building',
    rewardTitle: 'Watch any content you want',
    enjoymentTime: '3 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 93,
    title: 'SILENCE FEELS NORMAL',
    unlockRule: 'One full day without stimulation, panic, or avoidance',
    rewardTitle: 'Silence (intentional)',
    rewardLink: 'https://www.youtube.com/watch?v=JTEFKFiXSx4',
    enjoymentTime: '20 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 94,
    title: 'MONEY FEELS BORING',
    unlockRule: 'Money no longer changes your daily behavior',
    rewardTitle: 'Read: Wealth vs Income',
    rewardLink: 'https://en.wikipedia.org/wiki/Wealth',
    enjoymentTime: '25 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 95,
    title: 'WORK FEELS LIGHT',
    unlockRule: 'Execute hard tasks with low emotional resistance',
    rewardTitle: 'Watch any long-form creator you enjoy',
    enjoymentTime: '2 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 96,
    title: 'IDENTITY SHIFT CONFIRMED',
    unlockRule: 'Others describe you by what you build, not what you plan',
    rewardTitle: 'Identity theory',
    rewardLink: 'https://en.wikipedia.org/wiki/Identity_theory',
    enjoymentTime: '30 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 97,
    title: 'YOU TRUST YOURSELF',
    unlockRule: 'You keep a hard promise without external pressure',
    rewardTitle: 'Self-efficacy',
    rewardLink: 'https://en.wikipedia.org/wiki/Self-efficacy',
    enjoymentTime: '25 minutes',
    phase: 'irreversible-tier',
  },
  {
    id: 98,
    title: 'SYSTEM > MOOD (FINAL LOCK)',
    unlockRule: '30 days where execution ignores mood entirely',
    rewardTitle: 'Watch anything, anywhere',
    enjoymentTime: '3 hours',
    phase: 'irreversible-tier',
  },
  {
    id: 99,
    title: 'YEAR NOT WASTED',
    unlockRule: 'Clear proof: income, systems, identity all improved',
    rewardTitle: 'Full reflective evening',
    enjoymentTime: '3 hours',
    phase: 'irreversible-tier',
  },

  // ========== ELITE TIER - Rewards 100-150 ==========
  {
    id: 100,
    title: 'NEXT GAME UNLOCKED',
    unlockRule: 'You can clearly articulate the next decade, not just next year',
    rewardTitle: 'Read: The Long Now Foundation',
    rewardLink: 'https://longnow.org/',
    enjoymentTime: 'Unlimited that day only',
    phase: 'elite-tier',
  },
  {
    id: 101,
    title: 'First Four-Figure Proof',
    unlockRule: 'Earn a cumulative $1,000 USD from the cash engine (tracked, real payments).',
    rewardTitle: 'One full afternoon with zero execution pressure. You may go anywhere you feel comfortable.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 102,
    title: 'Founder Travel Signal',
    unlockRule: 'Research and document a real, viable business trip to another country (purpose, cost, contacts).',
    rewardTitle: 'Watch any full-length business or founder documentary of your choice.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 103,
    title: 'Capital Readiness Gate',
    unlockRule: 'Create a 1-page investor-ready startup brief (problem, solution, traction, ask).',
    rewardTitle: 'One premium long-form interview (top-tier founder or investor).',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 104,
    title: '100 Rejections Badge',
    unlockRule: 'Log 100 cumulative rejections (DMs, walk-ins, calls, or startup outreach).',
    rewardTitle: 'Evening out in a place that feels "above your current level."',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 105,
    title: 'Consistent Operator',
    unlockRule: '14 consecutive GREEN days (no discipline violations).',
    rewardTitle: 'Watch two Formula 1 race replays back-to-back.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 106,
    title: 'Authority Positioning',
    unlockRule: 'Publish one public authority asset (case study, breakdown, or teaching post).',
    rewardTitle: 'Free-choice YouTube deep dive (non-entertainment algorithm junk excluded).',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 107,
    title: 'First Outsider Validation',
    unlockRule: 'Receive unsolicited positive feedback from a customer or user (documented).',
    rewardTitle: 'One evening fully off-grid (no guilt).',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 108,
    title: 'Serious Money Week',
    unlockRule: 'Close two paid deals in the same week.',
    rewardTitle: 'Go somewhere you normally would not justify going.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 109,
    title: 'Passport Trigger',
    unlockRule: 'Apply for your passport (receipt or confirmation).',
    rewardTitle: 'Watch one full travel or lifestyle documentary.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 110,
    title: 'Sales System Builder',
    unlockRule: 'Build a repeatable outreach script + follow-up system and use it for 5 days.',
    rewardTitle: 'Any long-form podcast episode of your choice.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 111,
    title: 'Public Commitment Mark',
    unlockRule: 'Publicly state a clear 90-day business target.',
    rewardTitle: 'One premium film (cinema-quality).',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 112,
    title: '$2,500 Milestone',
    unlockRule: 'Reach $2,500 USD total revenue.',
    rewardTitle: 'Half-day freedom window.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 113,
    title: 'Startup User Proof',
    unlockRule: '25 real users OR 25 real conversations (logged).',
    rewardTitle: 'Watch any founder biopic or startup film.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 114,
    title: 'Pitch Mastery',
    unlockRule: 'Deliver 50 live pitches (any format).',
    rewardTitle: 'Attend any live or recorded business event/talk.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 115,
    title: 'Operational Calm',
    unlockRule: 'One full week where systems run without emotional volatility.',
    rewardTitle: 'Solo comfort experience (your choice of location).',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 116,
    title: 'First Delegate',
    unlockRule: 'Successfully delegate one task to another human.',
    rewardTitle: 'One premium interview marathon.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 117,
    title: 'Market Respect Signal',
    unlockRule: 'A business asks you for advice or help.',
    rewardTitle: 'Evening completely off work.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 118,
    title: 'Cash Engine Stability',
    unlockRule: 'Earn money 3 consecutive weeks without panic changes.',
    rewardTitle: 'One long creative or entertainment session.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 119,
    title: 'International Intent',
    unlockRule: 'Contact 5 foreign businesses or founders for collaboration.',
    rewardTitle: 'Travel-themed content session.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 120,
    title: '$5,000 Threshold',
    unlockRule: 'Cross $5,000 USD cumulative revenue.',
    rewardTitle: 'Full rest evening + premium content.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 121,
    title: 'Strategic Kill',
    unlockRule: 'Kill one idea or feature decisively and document why.',
    rewardTitle: 'Watch one high-intensity documentary or film.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 122,
    title: 'Fundraising Readiness',
    unlockRule: 'Prepare a real pitch deck (10–12 slides).',
    rewardTitle: 'Watch any investor AMA or summit talk.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 123,
    title: 'First External Mentor',
    unlockRule: 'Secure one mentor/advisor conversation.',
    rewardTitle: 'Relaxed social or solo outing.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 124,
    title: '$7,500 Proof',
    unlockRule: 'Reach $7,500 USD revenue.',
    rewardTitle: 'Half-day freedom.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 125,
    title: 'Brand Presence',
    unlockRule: 'Launch a consistent public brand channel (post 7 times).',
    rewardTitle: 'Any premium creator content.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 126,
    title: 'Founder Endurance',
    unlockRule: '30 days with zero rule violations.',
    rewardTitle: 'Watch an entire F1 race weekend coverage.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 127,
    title: 'Serious Negotiator',
    unlockRule: 'Close a deal above your previous price ceiling.',
    rewardTitle: 'Comfort experience upgrade.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 128,
    title: 'Cross-Border Vision',
    unlockRule: 'Finalize a real international expansion plan.',
    rewardTitle: 'Travel or global business documentary.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 129,
    title: '$10,000 Reality Shift',
    unlockRule: 'Reach $10,000 USD total revenue.',
    rewardTitle: 'One full day reduced workload.',
    enjoymentTime: '5 hours',
    phase: 'elite-tier',
  },
  {
    id: 130,
    title: 'Founder Reputation',
    unlockRule: 'Be publicly referenced or recommended.',
    rewardTitle: 'Any long premium media of choice.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 131,
    title: 'First Fund Ask',
    unlockRule: 'Make one real fundraising ask (angel, partner, or institution).',
    rewardTitle: 'Evening completely free.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 132,
    title: 'Geographic Expansion',
    unlockRule: 'Serve a client outside your city or country.',
    rewardTitle: 'Travel-inspired relaxation block.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 133,
    title: 'Systemized Freedom',
    unlockRule: 'One week where income is earned with <50% direct effort.',
    rewardTitle: 'Half-day enjoyment window.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 134,
    title: 'Identity Lock',
    unlockRule: 'Clearly documented "This is who I am now" statement.',
    rewardTitle: 'Watch one identity-shaping film.',
    enjoymentTime: '2.5 hours',
    phase: 'elite-tier',
  },
  {
    id: 135,
    title: '$15,000 Mark',
    unlockRule: 'Cross $15,000 USD revenue.',
    rewardTitle: 'Premium leisure experience.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 136,
    title: 'Market Authority',
    unlockRule: 'Speak or teach publicly once.',
    rewardTitle: 'Any long-form content.',
    enjoymentTime: '2 hours',
    phase: 'elite-tier',
  },
  {
    id: 137,
    title: 'Operational Leader',
    unlockRule: 'Run a full week as planner, not firefighter.',
    rewardTitle: 'Full evening free.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 138,
    title: 'International Booking',
    unlockRule: 'Confirm business travel (ticket or invitation).',
    rewardTitle: 'Celebration outing.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 139,
    title: '$20,000 Reality',
    unlockRule: 'Reach $20,000 USD total revenue.',
    rewardTitle: 'Full day decompression.',
    enjoymentTime: '5 hours',
    phase: 'elite-tier',
  },
  {
    id: 140,
    title: 'Funded Signal',
    unlockRule: 'Secure any external capital or grant.',
    rewardTitle: 'High-end documentary or film session.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 141,
    title: 'Long-Term Lock-In',
    unlockRule: 'Commit publicly to a 12-month roadmap.',
    rewardTitle: 'Any premium experience within bounds.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 142,
    title: 'International Presence',
    unlockRule: 'Physically attend a business event abroad.',
    rewardTitle: 'Full rest evening.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 143,
    title: '$25,000 Threshold',
    unlockRule: 'Cross $25,000 USD revenue.',
    rewardTitle: 'Half-day freedom.',
    enjoymentTime: '5 hours',
    phase: 'elite-tier',
  },
  {
    id: 144,
    title: 'Team Builder',
    unlockRule: 'Build a 2–3 person execution team.',
    rewardTitle: 'Comfort + entertainment block.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 145,
    title: 'Market Leader Signal',
    unlockRule: 'Outperform a known competitor.',
    rewardTitle: 'Any premium long-form content.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 146,
    title: 'Second Country Expansion',
    unlockRule: 'Operate actively in two countries.',
    rewardTitle: 'Celebration experience.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 147,
    title: '$35,000 Proof',
    unlockRule: 'Reach $35,000 USD revenue.',
    rewardTitle: 'Full day light-duty.',
    enjoymentTime: '6 hours',
    phase: 'elite-tier',
  },
  {
    id: 148,
    title: 'Irreversibility Moment',
    unlockRule: 'Business income exceeds survival threshold.',
    rewardTitle: 'Personal choice experience.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 149,
    title: 'Public Recognition',
    unlockRule: 'Media mention, award, or formal recognition.',
    rewardTitle: 'Premium documentary marathon.',
    enjoymentTime: '3 hours',
    phase: 'elite-tier',
  },
  {
    id: 150,
    title: 'Founder Identity Cemented',
    unlockRule: 'One full quarter executed without system changes.',
    rewardTitle: 'Full evening off.',
    enjoymentTime: '4 hours',
    phase: 'elite-tier',
  },
  {
    id: 151,
    title: 'Escape Velocity',
    unlockRule: 'You no longer question whether this path is real.',
    rewardTitle: 'Entire day lived on your terms.',
    enjoymentTime: '8 hours',
    phase: 'elite-tier',
  },
];

export function getRewardsByPhase(phase: VaultReward['phase']): VaultReward[] {
  return VAULT_REWARDS.filter(r => r.phase === phase);
}

export function getPhaseOrder(): VaultReward['phase'][] {
  return ['ignition', 'pressure-signal', 'proof-escalation', 'consolidation-signal', 'leverage-selection', 'irreversible-tier', 'elite-tier'];
}
